### ISSUE TITLE
May I ask if the complete code will be open-sourced？

### ISSUE THREAD

**Issue by attackoncs** [QwenLM/Qwen2-VL#10]
May I ask if the complete code will be open-sourced? If so, when will the complete code be open-sourced? I only found the open-sourced code of CodeQwen 1.5. I want to study the latest code. thanks-)

**Comment by jinze1994** [comment]
Of course, you can find our complete open-sourced code on [huggingface](https://github.com/huggingface/transformers/tree/main/src/transformers/models/qwen2_vl). More usage details are [here](https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#using---transformers-to-chat).
