### ISSUE TITLE
请问这个版本支持目标检测的检测框输出吗？

### ISSUE THREAD

**Issue by thunder95** [QwenLM/Qwen2-VL#102]
这个版本对图和视频理解增强了很多，但是不能像之前版本那样输出检测框，或者是我prompt不对吗？
我的prompt: 请输出人的检测框

**Comment by glz-11** [comment]
也是相同的问题。

**Comment by mokby** [comment]
我也是,而且SFT数据格式里面也没有给出方框的样例,怎么让模型学习呢?之前qwen-vl的SFT格式也变了

**Comment by kq-chen** [comment]
sft 数据格式可以参考 [#9](https://github.com/QwenLM/Qwen2-VL/issues/9#issuecomment-2334645753) 中的例子

**Comment by zxjzzz** [comment]
> 这个版本对图和视频理解增强了很多，但是不能像之前版本那样输出检测框，或者是我prompt不对吗？ 我的prompt: 请输出人的检测框

你好 请问有答案吗

**Comment by shelly-angel** [comment]
或许可以尝试这个prompt: Find all objects of the 'person' class in the image and return their bounding boxes in the format (x1, y1), (x2, y2). 我这边能用。

**Comment by syd168** [comment]
# pip install requests pillow matplotlib

import os
import base64
import requests
import json
import re
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np

# 配置API参数
OLLAMA_API_BASE = "http://localhost:11434"
MODEL_NAME = "qwen2.5vl:7b"

PROMPT = """
请检测图像中的所有火灾、烟雾和人员安全帽佩戴情况，并以坐标形式返回每个目标的位置。输出格式如下：

- 火灾对象：{"bbox_2d": [x1, y1, x2, y2], "label": "火灾", "sub_label": "轻微" / "中等" / "严重" / "不确定"}
- 烟雾对象：{"bbox_2d": [x1, y1, x2, y2], "label": "烟雾", "sub_label": "轻微" / "中等" / "严重" / "不确定"}
- 人员对象：{"bbox_2d": [x1, y1, x2, y2], "label": "人员", "sub_label": "佩戴安全帽" / "未佩戴安全帽" / "不确定"}

请严格按照上述格式输出所有检测到的对象及其坐标和属性，三类对象分别输出。如无法确定，请将 "sub_label" 设置为 "不确定"。

检测规则：
- 火灾：图像中存在明显火焰或燃烧迹象。
- 烟雾：图像中存在明显的烟雾扩散现象。
- 人员：图像中有完整或部分可见的人体。
- 安全帽佩戴：安全帽必须正确佩戴在头部，且帽檐朝前；若无法判断，则标记为 "不确定"。

注意事项：
- 输出结果应尽量准确。
- 输出检测到的对象不要超过 10 个。

结果示例：
[
    {"bbox_2d": [100, 200, 180, 300], "label": "火灾", "sub_label": "严重"},
    {"bbox_2d": [220, 150, 350, 280], "label": "烟雾", "sub_label": "轻微"},
    {"bbox_2d": [400, 320, 480, 420], "label": "人员", "sub_label": "佩戴安全帽"},
    {"bbox_2d": [520, 330, 600, 430], "label": "人员", "sub_label": "未佩戴安全帽"}
]
"""


def call_ollama_vision(model: str, messages: list) -> str:
    """调用 Ollama 视觉模型"""
    url = f"{OLLAMA_API_BASE}/api/chat"
    data = {
        "model": model,
        "messages": messages,
        "stream": False
    }

    try:
        response = requests.post(url, json=data)
        response.raise_for_status()
        result = response.json()
        return result.get("message", {}).get("content", "")
    except Exception as e:
        return f"调用 Ollama 失败: {str(e)}"


def is_url(path: str) -> bool:
    return path.startswith("http://") or path.startswith("https://")


def encode_image_to_base64(image_path: str) -> str:
    with open(image_path, "rb") as f:
        encoded_image = base64.b64encode(f.read())
    encoded_image_text = encoded_image.decode("utf-8")
    ext = os.path.splitext(image_path)[-1].lower().replace('.', '')
    if ext == 'jpg':
        ext = 'jpeg'
    return f"data:image/{ext};base64,{encoded_image_text}"


def detect_image(image: str, prompt: str = PROMPT) -> str:
    """使用 Ollama 检测图像"""
    if is_url(image):
        # 对于 URL 图像，需要先下载
        try:
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
            }
            response = requests.get(image, headers=headers, timeout=30)
            response.raise_for_status()
            image_data = base64.b64encode(response.content).decode('utf-8')
        except Exception as e:
            return f"下载图像失败: {str(e)}"
    else:
        # 检查本地图像文件是否存在
        if not os.path.exists(image):
            return f"本地图像文件不存在: {image}"

        try:
            # 对于本地图像，直接编码
            image_data = encode_image_to_base64(image).split(',')[1]  # 移除 data:image/...;base64, 前缀
        except Exception as e:
            return f"读取本地图像失败: {str(e)}"

    messages = [
        {
            "role": "user",
            "content": prompt,
            "images": [image_data]
        }
    ]

    return call_ollama_vision(MODEL_NAME, messages)


def extract_json_array(text: str):
    """从文本中提取第一个完整的JSON数组字符串"""
    text = text.replace('```json', '').replace('```', '').strip()
    start = text.find('[')
    if start == -1:
        return None

    bracket_count = 0
    for i in range(start, len(text)):
        if text[i] == '[':
            bracket_count += 1
        elif text[i] == ']':
            bracket_count -= 1
            if bracket_count == 0:
                return text[start:i + 1]
    return None


def try_fix_json(text: str) -> str:
    """尝试修复常见的JSON格式错误"""
    text = text.replace('"', '"').replace('"', '"').replace("'", "'").replace("'", "'")
    text = re.sub(r',\s*([\]}])', r'\1', text)
    text = re.sub(r'("[\]}])\s*("[a-zA-Z_]+"\s*:)', r'\1, \2', text)
    return text


def parse_detection_result(result: str):
    """解析检测结果，返回对象列表或错误信息"""
    try:
        return json.loads(result)
    except json.JSONDecodeError:
        json_part = extract_json_array(result)
        if json_part:
            try:
                return json.loads(json_part)
            except json.JSONDecodeError:
                try:
                    fixed = try_fix_json(json_part)
                    return json.loads(fixed)
                except json.JSONDecodeError as e:
                    print(f"JSON解析失败: {str(e)}\n原始内容: {json_part}")
                    return None
        return None


def visualize_detection(image_path: str, detection_result: str, show_window: bool = True):
    """可视化检测结果"""
    # 解析检测结果
    parsed_result = parse_detection_result(detection_result)

    if not parsed_result or not isinstance(parsed_result, list):
        print("⚠️  无法解析检测结果，跳过可视化")
        return

    # 过滤有效检测结果
    valid_detections = []
    for obj in parsed_result:
        if (isinstance(obj, dict) and
                'bbox_2d' in obj and
                'label' in obj and
                'sub_label' in obj and
                len(obj['bbox_2d']) == 4 and
                obj['sub_label'] != '不确定'):
            valid_detections.append(obj)

    if not valid_detections:
        print("📭 没有检测到有效目标，跳过可视化")
        return

    try:
        # 加载图像
        if is_url(image_path):
            # 对于URL图像，需要重新下载
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
            }
            response = requests.get(image_path, headers=headers, timeout=30)
            response.raise_for_status()
            from io import BytesIO
            img = Image.open(BytesIO(response.content)).convert('RGB')
        else:
            img = Image.open(image_path).convert('RGB')

        # 转换为numpy数组
        img_array = np.array(img)

        # 创建matplotlib图形
        fig, ax = plt.subplots(1, 1, figsize=(12, 8))
        ax.imshow(img_array)

        # 颜色映射
        color_map = {
            "火灾": "red",
            "烟雾": "blue",
            "人员": "green"
        }

        # 绘制检测框和标签
        detection_count = 0
        for obj in valid_detections:
            bbox = obj['bbox_2d']
            label = obj['label']
            sub_label = obj['sub_label']

            x1, y1, x2, y2 = bbox
            width = x2 - x1
            height = y2 - y1

            # 选择颜色
            color = color_map.get(label, 'gray')

            # 绘制边界框
            rect = patches.Rectangle((x1, y1), width, height,
                                     linewidth=2, edgecolor=color,
                                     facecolor='none', alpha=0.8)
            ax.add_patch(rect)

            # 添加标签
            text = f"{label}: {sub_label}"
            ax.text(x1, y1 - 5, text, fontsize=10, color='white',
                    bbox=dict(boxstyle="round,pad=0.3", facecolor=color, alpha=0.7),
                    fontweight='bold')

            detection_count += 1

        # 设置图像标题
        title = f"检测结果 - 发现 {detection_count} 个目标"
        if not is_url(image_path):
            title += f" ({os.path.basename(image_path)})"
        ax.set_title(title, fontsize=14, fontweight='bold')

        # 移除坐标轴
        ax.axis('off')

        # 调整布局
        plt.tight_layout()

        if show_window:
            # 显示图像窗口
            plt.show()

        print(f"🖼️  已显示检测结果图像（{detection_count} 个目标）")

    except Exception as e:
        print(f"❌ 可视化失败: {str(e)}")


def get_available_images():
    """获取可用的本地图片"""
    image_dir = "images"
    if not os.path.exists(image_dir):
        os.makedirs(image_dir)
        print(f"📁 已创建 {image_dir} 目录")

    # 支持的图片格式
    supported_formats = ('.png', '.jpg', '.jpeg', '.bmp', '.gif', '.tiff')
    images = []

    if os.path.exists(image_dir):
        for file in os.listdir(image_dir):
            if file.lower().endswith(supported_formats):
                images.append(os.path.join(image_dir, file))

    return images


def main():
    # 自动检测本地图片
    local_images = get_available_images()

    # 如果没有本地图片，提供提示
    if not local_images:
        print("📌 提示: 请将图片文件放到 'images' 目录中")
        print("   支持格式: .png, .jpg, .jpeg, .bmp, .gif, .tiff")
        print("   或者修改 url_images 列表添加网络图片URL\n")

    # 网络图片示例（使用更可靠的图片源）
    url_images = [
        # 可在此添加需要检测的互联网图片URL
        # "https://example.com/image.jpg"  # 请替换为有效的图片URL
    ]

    all_images = local_images + url_images

    if not all_images:
        print("❌ 没有找到可检测的图片")
        print("💡 请:")
        print("   1. 将图片放到 'images' 目录中, 或")
        print("   2. 在 url_images 列表中添加有效的图片URL")
        return

    print(f"🔍 开始检测 {len(all_images)} 张图片（本地: {len(local_images)}, 网络: {len(url_images)}）\n")

    results = []
    for i, img in enumerate(all_images, 1):
        print(f"[{i}/{len(all_images)}] 检测图片: {img}")
        try:
            result = detect_image(img)
            print(f"✅ 检测完成")
            print(f"📋 结果: {result}")
            results.append({"image": img, "result": result})

            # 检测到结果后自动显示可视化
            if not result.startswith(
                    ("检测失败", "下载图像失败", "本地图像文件不存在", "读取本地图像失败", "调用 Ollama 失败")):
                print("🎨 生成可视化图像...")
                visualize_detection(img, result)

        except Exception as e:
            print(f"❌ 检测失败: {e}")
            results.append({"image": img, "result": f"检测失败: {e}"})
        print("-" * 50)

    print(f"\n🎯 检测完成! 共处理 {len(results)} 张图片")
    success_count = len([r for r in results if not r["result"].startswith(
        ("检测失败", "下载图像失败", "本地图像文件不存在", "读取本地图像失败"))])
    print(f"✅ 成功: {success_count}, ❌ 失败: {len(results) - success_count}")


if __name__ == "__main__":
    from utils import setup_chinese_font
    setup_chinese_font()
    main()

**Comment by syd168** [comment]
PROMPT = """
请检测图像中的所有的......，并以坐标形式返回每个目标的位置。输出格式如下：

- 对象1：{"bbox_2d": [x1, y1, x2, y2], "label": "对象1名",}
- 对象2：{"bbox_2d": [x1, y1, x2, y2], "label": "对象2名", "sub_label": "类1" / "类2" / "不确定"}

请严格按照上述格式输出所有检测到的对象及其坐标和属性，三类对象分别输出。如无法确定，请将 "sub_label" 设置为 "不确定"。

检测规则：
- 对象1：图像中存在对象1的迹象。
- 对象2：图像中存在对象2的迹象，并根据.....进行分类，      ...........................更多描述..........................。


注意事项：
- 输出结果要尽可能准确，而且严格按照上面要求的规范输出。
- 输出检测到的对象不要超过 XXXXXXXXXXXXXXXXXX 个。

结果示例：
[
    {"bbox_2d": [100, 200, 180, 300], "label": "对象1"},
    {"bbox_2d": [220, 150, 350, 280], "label": "对象2", "sub_label": "实际子类名称"},
]
"""
