### ISSUE TITLE
无法识别棕色的图片

### ISSUE THREAD

**Issue by xihongshi153** [QwenLM/Qwen2-VL#108]
`curl --location --request POST 'XXXXXXXXX/chat/completions' \
--header 'Content-Type: application/json' \
--data-raw '{
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAUUlEQVR42u3PMQ0AMAgAMJhWNKEJWVPBQdI6aE5XXPbiOAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAYF9HxNPAkL6NC7PAAAAAElFTkSuQmCC"
                    }
                },
                {
                    "type": "text",
                    "text": "这张图片里面有什么？"
                }
            ]
        }
    ]
}'`
### 图片
![decoded_image](https://github.com/user-attachments/assets/8e25fdfc-4986-429e-93d1-26e24fb277db)

大模型有但不限于以下回答：
1. 这张图片是纯黑色的。
2. 这张图片是纯白色的。
3. 这张图片显示了一个蓝色的圆圈，圆圈内部是黑色的。这个图形可能是某种符号、标志或者图标的一部分。

## 问题
请问为什么无法识别棕色的图片？

**Comment by logicwong** [comment]
定位到是分辨率的问题，我们的模型在比较小的分辨率下识别不太准确，建议min_pixels放大以取得更好的效果（我们后续也会分析这一现象）

我将分辨率放大到196x196后识别就正确了
![4209508D-5566-4411-A476-69A5DD2030F6](https://github.com/user-attachments/assets/954e2644-ca93-4576-80a6-0101fe64761b)
