### ISSUE TITLE
How can we SFT Qwen2-VL on videos ? 

### ISSUE THREAD

**Issue by zhshj0110** [QwenLM/Qwen2-VL#109]
Thanks for the awesome works.
We noticed that  the script for supervised finetuning Qwen2-VL with LLaMA-Factory are provide. However, will the training script support video input in the future?

**Comment by hiyouga** [comment]
We have supported video finetuning https://github.com/hiyouga/LLaMA-Factory/tree/main/data#multimodal-video-dataset-1

**Comment by zhangfaen** [comment]
one alternative is https://github.com/zhangfaen/finetune-Qwen2-VL  fyi
