### ISSUE TITLE
License for code in repository

### ISSUE THREAD

**Issue by kachiO** [QwenLM/Qwen2-VL#111]
Hi, 
I see the model weights license is Apache 2.0. What is the license for using the code in this repo? Can you please add the license?

**Comment by ShuaiBai623** [comment]
apache 2.0

**Comment by kachiO** [comment]
Thank you. If it's not too much trouble, can you please add the license file to the repo?

**Comment by shaform** [comment]
@kachiO 
> I see the model weights license is Apache 2.0. 
It seems some model weights are not licensed in Apache 2.0. See #963.
