### ISSUE TITLE
创建了一个相关的多模态大模型交流群，有需要可以加我微信拉入群

### ISSUE THREAD

**Issue by feihuamantian** [QwenLM/Qwen2-VL#115]
可以扫二维码入群，或是加我微信拉入群：yx116169
![20240822-142406](https://github.com/user-attachments/assets/8537b5c6-2986-49be-a3cf-12590b7cd907)

**Comment by XavierHeart** [comment]
哥 我也想加，二维码过期了

**Comment by glz-11** [comment]
再发一下，魔塔应该弄个沟通区
