### ISSUE TITLE
您好，请问有针对图片大小的BenchMark吗？

### ISSUE THREAD

**Issue by xihongshi153** [QwenLM/Qwen2-VL#125]
显卡配置：A10
您好，我在本地使用vllm部署Qwen2-VL-2B-Instruct-AWQ，
分别测试150kb，500kb，800kb，1mb图片。

我发现800kb的图片的吞吐量最大。

所以请问有针对图片大小的BenchMark？我想看看这个规律是否真实存在。

**Comment by logicwong** [comment]
显存占用跟分辨率大小比较有关
