### ISSUE TITLE
web_demo_mm.py加载Qwen2-2B显存不足问题

### ISSUE THREAD

**Issue by Guangming92** [QwenLM/Qwen2-VL#130]
按照提供的案例，进行本地模型加载，模型加载成功，但是在对图片内容进行描述的时候提示，显存不足
显卡4090，两张，显存24G单张
![image](https://github.com/user-attachments/assets/e9f32e52-cf88-4b3f-82c5-76992abd10cc)
![image](https://github.com/user-attachments/assets/dff80485-62b8-4c6a-b38c-ea699a7a75f6)
请帮忙看下是什么原因，或是需要添加什么参数？

**Comment by LMJOK** [comment]
> 按照提供的案例，进行本地模型加载，模型加载成功，但是在对图片内容进行描述的时候提示，显存不足 显卡4090，两张，显存24G单张 ![image](https://private-user-images.githubusercontent.com/57172408/365061458-e9f32e52-cf88-4b3f-82c5-76992abd10cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjAxNjUsIm5iZiI6MTcyNjkxOTg2NSwicGF0aCI6Ii81NzE3MjQwOC8zNjUwNjE0NTgtZTlmMzJlNTItY2Y4OC00YjNmLTgyYzUtNzY5OTJhYmQxMGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDExNTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MTBiYzc5MWYwNjBjNDAzMmFiZTRjN2VhMjZkODRmNmU3MDI4MDg5ODYyZmRjMjZhMmYwZDI2M2RiYmM4MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jfePcO5ab3CHqGaxyx2S92mwpVkapRebQWtgFTN6_H4) ![image](https://private-user-images.githubusercontent.com/57172408/365061518-dff80485-62b8-4c6a-b38c-ea699a7a75f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjAxNjUsIm5iZiI6MTcyNjkxOTg2NSwicGF0aCI6Ii81NzE3MjQwOC8zNjUwNjE1MTgtZGZmODA0ODUtNjJiOC00YzZhLWIzOGMtZWE2OTlhN2E3NWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDExNTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMzI1ZWQwNTYzNzkyMTMwMzNkY2NjMjAzOTA3NTMxYTA3NmZmMTk5YmRlNDcwMjkxM2I3OTJhMjEzYzIyZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AzuWR6qvG33wV09bg3nyjrIwRPFjReT5Rk4ZGjCM_rw) 请帮忙看下是什么原因，或是需要添加什么参数？

Have you solved it? What parameters do you need to add
