### ISSUE TITLE
Video loading too slow

### ISSUE THREAD

**Issue by xiaosu-zhu** [QwenLM/Qwen2-VL#131]
Currently the video loading function is implemented by `io.read_video`, which is extremely slow. When I provide a 12min, 38.4MB video, it reads for ~1min to provide the output.

It is recommended to use PyPI `decord` library for video loading. The core change could be:

```python
# qwen_vl_utils/vision_process.py

from decord import VideoReader
...
...

def fetch_video(ele: dict, size_factor: int = FRAME_FACTOR) -> torch.Tensor | list[Image.Image]:
    if isinstance(ele["video"], str):
        # TODO: support http url

        video = ele["video"]
        if video.startswith("file://"):
            video = video[7:]

        vr = VideoReader(video)
        video_fps = vr.get_avg_fps()
        ...
        ...
        idx = torch.linspace(0, len(vr) - 1, nframes).round().long()
        raw_pixels = vr.get_batch(idx)
        # [TCHW]
        raw_pixels = raw_pixels.permute(0, 3, 1, 2)
        height, width = raw_pixels.shape[2:]
        ...
        raw_pixels = transforms.functional.resize(
            raw_pixels,
            [resized_height, resized_width],
            interpolation=InterpolationMode.BICUBIC,
            antialias=True,
        ).float()
        return raw_pixels
```

By changing to `decord.VideoReader`, the reading time could be significantly reduced. From ~1min to <1sec.

**Comment by kq-chen** [comment]
Thank you for your suggestion. Based on the information you provided, `decord` has now been added to `qwen-vl-utils` as an optional feature. you can install it with
```bash
pip install qwen-vl-utils[decord]
```

also, you can use `FORCE_QWENVL_VIDEO_READER=torchvision` or `FORCE_QWENVL_VIDEO_READER=decord` to change the backend from the default.
