### ISSUE TITLE
 Open-source plan

### ISSUE THREAD

**Issue by yangjiabupt** [QwenLM/Qwen2-VL#14]
Could you please let me know what your open-source plan for the training code looks like? How long will it approximately take to open-source it, for example, within a month or within three months?

**Comment by jinze1994** [comment]
We will open-source the Qwen2-VL-72B soon. We also provide the script for supervised training of our model by [Llama-factory](https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#training).
