### ISSUE TITLE
QWen2-VL针对视频推理的帧数推荐

### ISSUE THREAD

**Issue by Lanbai-eleven** [QwenLM/Qwen2-VL#147]
使用QWen2-VL进行视频抽帧进行多图片处理所能容许的最大上限大概是多少，这是否有参考值？
以及预处理图像的时候是否有什么通用的尺寸，例如512*512.

**Comment by logicwong** [comment]
@Lanbai-eleven 直接参考这个文件即可 https://github.com/QwenLM/Qwen2-VL/blob/main/qwen-vl-utils/src/qwen_vl_utils/vision_process.py
