### ISSUE TITLE
在sft的时候，请问视觉处理的部分图片做过resize嘛

### ISSUE THREAD

**Issue by digbangbang** [QwenLM/Qwen2-VL#149]
我运行代码的时候报错需要长和宽超过28

于是我接着在准备数据集的时候，特意过滤了图片的size，让长和宽都超过200，但是仍有一些图片报错，并说我的图片宽只有15，需要超过28
<img width="1301" alt="image" src="https://github.com/user-attachments/assets/06693caa-f163-4f26-b8fd-b4cb424dd697">

是有一些图片的处理我没注意到吗

**Comment by hiyouga** [comment]
请更新 LLaMA-Factory https://github.com/hiyouga/LLaMA-Factory

**Comment by digbangbang** [comment]
已找到问题，image会重新进行resize，所以长宽比不能过大或过小，否则其中一个会被resize到很小。

**Comment by yuan-QAQ** [comment]
> 已找到问题，image会重新进行resize，所以长宽比不能过大或过小，否则其中一个会被resize到很小。

请问在哪会重新resize呢？

**Comment by digbangbang** [comment]
https://github.com/hiyouga/LLaMA-Factory/blob/a76617728a1fecefb959a2f25d1ffbff22a56dc1/src/llamafactory/data/mm_plugin.py#L72
