### ISSUE TITLE
The number of images does not match the number of {} tokens".format(IMAGE_PLACEHOLDER)

### ISSUE THREAD

**Issue by 942518154** [QwenLM/Qwen2-VL#152]
使用LlamaFactory对Qwen2VL-2B在数据集swift/llava-med-zh-instruct-60k进行训练时加载数据集报错，请问该如何解决

报错为：
![111](https://github.com/user-attachments/assets/8e3c4ff7-b387-4b10-b24c-18e9d2acc0e0)

**Comment by Yangfan-96** [comment]
你好，我想问下这个问题是怎么解决的呢

**Comment by 942518154** [comment]
我当时没有解决，后面换用魔塔的[ms-swift](https://github.com/modelscope/ms-swift)这个框架来训练就没有报错问题，也可以训练


> 你好，我想问下这个问题是怎么解决的呢

**Comment by hktime** [comment]
检查下数据集里每条样本的images数量和<image>标签数量是否是一致的

> 你好，我想问下这个问题是怎么解决的呢
