### ISSUE TITLE
请问下载模型一直报签名错误是什么情况？

### ISSUE THREAD

**Issue by leavegee** [QwenLM/Qwen2-VL#16]
modelscope.hub.errors.FileIntegrityError: File /home/apple/.cache/modelscope/hub/._____temp/qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4/model-00002-of-00002.safetensors integrity check failed, expected sha256 signature is e41d9af09037c50f37b14d9f20b04f984ebde3259545641aa8206b8c21361b20, actual is ec708eee6fed25eb9924486d990f9807d132d0c12bb240bb032042b898ee1199, the download may be incomplete, please try again.

请问如何解决呢？

**Comment by yingdachen** [comment]
> modelscope.hub.errors.FileIntegrityError: File /home/apple/.cache/modelscope/hub/._____temp/qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4/model-00002-of-00002.safetensors integrity check failed, expected sha256 signature is e41d9af09037c50f37b14d9f20b04f984ebde3259545641aa8206b8c21361b20, actual is ec708eee6fed25eb9924486d990f9807d132d0c12bb240bb032042b898ee1199, the download may be incomplete, please try again.
> 
> 请问如何解决呢？

please refer to discussion on modelscope github: https://github.com/modelscope/modelscope/issues/968
