### ISSUE TITLE
qwen2-vl-7b llamafactory微调，数据集只支持单张图片吗

### ISSUE THREAD

**Issue by gujiacheng** [QwenLM/Qwen2-VL#170]
单轮多张、多轮多张不支持吗？

**Comment by gujiacheng** [comment]
https://github.com/hiyouga/LLaMA-Factory/issues/3739

**Comment by gujiacheng** [comment]
多张图片训练就会报错，完整的报错trace：
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]
  0%|▏                                                                                                                                                                                        | 1/1250 [00:43<15:08:21, 43.64s/it][rank2]: Traceback (most recent call last):
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/llamafactory/launcher.py", line 23, in <module>
[rank2]:     launch()
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/llamafactory/launcher.py", line 19, in launch
[rank2]:     run_exp()
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/llamafactory/train/tuner.py", line 50, in run_exp
[rank2]:     run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/llamafactory/train/sft/workflow.py", line 95, in run_sft
[rank2]:     train_result = trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1991, in train
[rank2]:     return inner_training_loop(
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2332, in _inner_training_loop
[rank2]:     tr_loss_step = self.training_step(model, inputs)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 3416, in training_step
[rank2]:     loss = self.compute_loss(model, inputs)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 3463, in compute_loss
[rank2]:     outputs = model(**inputs)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank2]:     ret_val = func(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1846, in forward
[rank2]:     loss = self.module(*inputs, **kwargs)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1589, in forward
[rank2]:     inputs_embeds[image_mask] = image_embeds
[rank2]: RuntimeError: shape mismatch: value tensor of shape [2376, 3584] cannot be broadcast to indexing result of shape [809, 3584]

**Comment by hiyouga** [comment]
Try increasing `cutoff_len` parameter
