### ISSUE TITLE
qwen2-vl-7B-instruct输入类型为"image"时,报"Unknown part type: image"错误

### ISSUE THREAD

**Issue by yangxin60-tal** [QwenLM/Qwen2-VL#174]
'{"object":"error","message":"Unknown part type: image","type":"BadRequestError","param":null,"code":400}'

**Comment by fyabc** [comment]
@yangxin60-tal 您好，可以提供一下详细的复现方法和错误信息吗？

**Comment by yangxin60-tal** [comment]
def process_image(image, shouldConvert=False):
    # 获取上传文件的目录
    global math_messages
    math_messages = [] # reset when upload image
    # uploaded_file_dir = os.environ.get("GRADIO_TEMP_DIR") or str(
    #     Path(tempfile.gettempdir()) / "gradio"
    # )
    # os.makedirs(uploaded_file_dir, exist_ok=True)
    
    # # 创建临时文件路径
    # name = f"tmp{secrets.token_hex(20)}.jpg"
    # filename = os.path.join(uploaded_file_dir, name)
    filename = image
    # 保存上传的图片
    if shouldConvert:
        new_img = Image.new("RGB", size=(image.width, image.height), color=(255, 255, 255))
        new_img.paste(image, (0, 0), mask=image)
        image = new_img
    # image.save(filename)
    
    # 调用qwen-vl-max-0809模型处理图片
    messages = [
        {"role": "system","content":"You are a helpful assistant."}, 
        {"role": "user","content": [
            {"type": "image","image": f"file://{filename}"},
            {"type": "text","text": "Please describe the math-related content in this image, ensuring that any LaTeX formulas are correctly transcribed. Non-mathematical details do not need to be described."}
        ]
        }
    ]
    payload = json.dumps({
        "model": "Qwen2-VL-7B-Instruct",
        "messages": messages
        })

    response = requests.request("POST", vl_url, headers=headers, data=payload)
    response_dict = json.loads(response.text)
    content = response_dict["choices"][0]["message"]["content"]
    # response = MultiModalConversation.call(model="qwen-vl-max-0809", messages=messages)
    # # 清理临时文件
    # os.remove(filename)
    # return response.output.choices[0]["message"]["content"]
    return content


&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Sep 11, 2024 02:38 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [QwenLM/Qwen2-VL] qwen2-vl-7B-instruct输入类型为"image"时,报"Unknown part type: image"错误 (Issue #174)

&nbsp;



 
@yangxin60-tal 您好，可以提供一下详细的复现方法和错误信息吗？

**Comment by yangxin60-tal** [comment]
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Sep 11, 2024 02:38 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [QwenLM/Qwen2-VL] qwen2-vl-7B-instruct输入类型为"image"时,报"Unknown part type: image"错误 (Issue #174)

&nbsp;



 
@yangxin60-tal 您好，可以提供一下详细的复现方法和错误信息吗？

**Comment by yangxin60-tal** [comment]
> &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: &nbsp;Wed, Sep 11, 2024 02:38 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; ***@***.***&gt;; Subject: &nbsp;Re: [QwenLM/Qwen2-VL] qwen2-vl-7B-instruct输入类型为"image"时,报"Unknown part type: image"错误 (Issue #174) &nbsp; @yangxin60-tal 您好，可以提供一下详细的复现方法和错误信息吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

type换成image_url就没问题

**Comment by yangxin60-tal** [comment]
> @yangxin60-tal 您好，可以提供一下详细的复现方法和错误信息吗？
<img width="649" alt="image" src="https://github.com/user-attachments/assets/5978c5cb-0fe5-4716-9b5a-a5cc452ebeb1">
type设为image_url就没问题

**Comment by fyabc** [comment]
@yangxin60-tal 您好，您似乎使用的是vllm openai api server，这个目前是严格按照openai api接口规则处理的，因此不能使用"image"属性，必须使用"image_url"格式。

**Comment by yangxin60-tal** [comment]
部署方式确实是vllm openai api server，请问用什么方式部署才能使用image属性呢？
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Sep 11, 2024 02:58 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [QwenLM/Qwen2-VL] qwen2-vl-7B-instruct输入类型为"image"时,报"Unknown part type: image"错误 (Issue #174)

&nbsp;



 
@yangxin60-tal 您好，您似乎使用的是vllm openai api server，这个目前是严格按照openai api接口规则处理的，因此不能使用"image"属性，必须使用"image_url"格式。

**Comment by fyabc** [comment]
@yangxin60-tal 您好，参考[此处](https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#web-ui-example)部署`web_demo_mm.py`，可使用image属性。
当然，该脚本基于HF推理，速度慢于vllm部署，也可考虑在调用vllm服务的时候手动适配下格式。

**Comment by jiezhangGt** [comment]
> @yangxin60-tal 您好，参考[此处](https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#web-ui-example)部署`web_demo_mm.py`，可使用image属性。 当然，该脚本基于HF推理，速度慢于vllm部署，也可考虑在调用vllm服务的时候手动适配下格式。

请问后续有计划vllm openai api server支持"image"属性吗？

**Comment by jiezhangGt** [comment]
其实是支持的


> @yangxin60-tal 您好，您似乎使用的是vllm openai api server，这个目前是严格按照openai api接口规则处理的，因此不能使用"image"属性，必须使用"image_url"格式。

支持的，你将图片的base64得到（即base64_string），按以下格式请求即可：

    "messages": [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": [
            {"type": "image_url", "image_url": {"url":f"data:image,{base64_string}"}},
            {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
        ]}

**Comment by jiezhangGt** [comment]
> 其实是支持的
> 
> > @yangxin60-tal 您好，您似乎使用的是vllm openai api server，这个目前是严格按照openai api接口规则处理的，因此不能使用"image"属性，必须使用"image_url"格式。
> 
> 支持的，你将图片的base64得到（即base64_string），按以下格式请求即可：
> 
> ```
> "messages": [
>     {"role": "system", "content": "You are a helpful assistant."},
>     {"role": "user", "content": [
>         {"type": "image_url", "image_url": {"url":f"data:image,{base64_string}"}},
>         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
>     ]}
> ```


再麻烦一些的话，可以修改vllm的底层代码：/****/python3.10/site-packages/vllm/entrypoints/chat_utils.py

```python
def _parse_chat_message_content_parts(
    role: str,
    parts: Iterable[ChatCompletionContentPartParam],
    mm_tracker: BaseMultiModalItemTracker,
) -> List[ConversationMessage]:
    texts: List[str] = []

    mm_parser = mm_tracker.create_parser()

    for part in parts:
        part_type = part["type"]
        if part_type == "text":
            text = _TextParser(part)["text"]
            texts.append(text)
        elif part_type == "image_url":
            image_url = _ImageParser(part)["image_url"]

            if image_url.get("detail", "auto") != "auto":
                logger.warning(
                    "'image_url.detail' is currently not supported and "
                    "will be ignored.")

            mm_parser.parse_image(image_url["url"])


        # elif part_type == "image":
        #     image = _TextParser(part)["text"]
        #     mm_parser.parse_image(image)


        elif part_type == "audio_url":
            audio_url = _AudioParser(part)["audio_url"]

            mm_parser.parse_audio(audio_url["url"])
        elif part_type == "refusal":
            text = _RefusalParser(part)["refusal"]
            texts.append(text)
        else:
            raise NotImplementedError(f"Unknown part type: {part_type}")

    text_prompt = "\n".join(texts)
    mm_placeholder_counts = mm_parser.mm_placeholder_counts()
    if mm_placeholder_counts:
        text_prompt = _get_full_multimodal_text_prompt(mm_placeholder_counts,
                                                       text_prompt)

    return [ConversationMessage(role=role, content=text_prompt)]
```

注释部分是需要添加的代码，去掉注释后，就可以image请求了


```python
"messages": [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": [
        {"type": "image", "image": f"data:image,{base64_string}"},
        {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
    ]}
```

**Comment by yangxin60-tal** [comment]
> > 其实是支持的
> > > @yangxin60-tal 您好，您似乎使用的是vllm openai api server，这个目前是严格按照openai api接口规则处理的，因此不能使用"image"属性，必须使用"image_url"格式。
> > 
> > 
> > 支持的，你将图片的base64得到（即base64_string），按以下格式请求即可：
> > ```
> > "messages": [
> >     {"role": "system", "content": "You are a helpful assistant."},
> >     {"role": "user", "content": [
> >         {"type": "image_url", "image_url": {"url":f"data:image,{base64_string}"}},
> >         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
> >     ]}
> > ```
> 
> 再麻烦一些的话，可以修改vllm的底层代码： 修改1. /****/python3.10/site-packages/vllm/entrypoints/chat_utils.py
> 
> ```python
> def _parse_chat_message_content_parts(
>     role: str,
>     parts: Iterable[ChatCompletionContentPartParam],
>     mm_tracker: BaseMultiModalItemTracker,
> ) -> List[ConversationMessage]:
>     texts: List[str] = []
> 
>     mm_parser = mm_tracker.create_parser()
> 
>     for part in parts:
>         part_type = part["type"]
>         if part_type == "text":
>             text = _TextParser(part)["text"]
>             texts.append(text)
>         elif part_type == "image_url":
>             image_url = _ImageParser(part)["image_url"]
> 
>             if image_url.get("detail", "auto") != "auto":
>                 logger.warning(
>                     "'image_url.detail' is currently not supported and "
>                     "will be ignored.")
> 
>             mm_parser.parse_image(image_url["url"])
> 
> 
>         # elif part_type == "image":
>         #     image = _TextParser(part)["text"]
>         #     mm_parser.parse_image(image)
> 
> 
>         elif part_type == "audio_url":
>             audio_url = _AudioParser(part)["audio_url"]
> 
>             mm_parser.parse_audio(audio_url["url"])
>         elif part_type == "refusal":
>             text = _RefusalParser(part)["refusal"]
>             texts.append(text)
>         else:
>             raise NotImplementedError(f"Unknown part type: {part_type}")
> 
>     text_prompt = "\n".join(texts)
>     mm_placeholder_counts = mm_parser.mm_placeholder_counts()
>     if mm_placeholder_counts:
>         text_prompt = _get_full_multimodal_text_prompt(mm_placeholder_counts,
>                                                        text_prompt)
> 
>     return [ConversationMessage(role=role, content=text_prompt)]
> ```
> 
> 注释部分是需要添加的代码，去掉注释即可
> 
> 修改2. /****/python3.10/site-packages/vllm/multimodal/utils.py
> 
> ```python
> # import base64
> # import os
> # def image_to_base64(image_path):
> #     with open(image_path, "rb") as image_file:
> #         # 读取图片文件并将其编码为Base64
> #         encoded_string = base64.b64encode(image_file.read())
> #         # 将字节类型的Base64编码转换为字符串
> #         encoded_string = encoded_string.decode('utf-8')
> #     return encoded_string
> 
> async def async_fetch_image(image_url: str,
>                             *,
>                             image_mode: str = "RGB") -> Image.Image:
>     """
>     Asynchronously load a PIL image from a HTTP or base64 data URL.
> 
>     By default, the image is converted into RGB format.
>     """
>     if image_url.startswith('http'):
>         image_raw = await global_http_connection.async_get_bytes(
>             image_url, timeout=VLLM_IMAGE_FETCH_TIMEOUT)
>         image = _load_image_from_bytes(image_raw)
> 
>     elif image_url.startswith('data:image'):
>         image = _load_image_from_data_url(image_url)
>     # elif os.path.exists(image_url):
>     #     image_base64 = image_to_base64(image_url)
>     #     image = load_image_from_base64(image_base64)
>     else:
>         raise ValueError("Invalid 'image_url': A valid 'image_url' must start "
>                          "with either 'data:image' or 'http'.")
> 
>     return image.convert(image_mode)
> ```
> 
> 注释部分是需要添加的代码，去掉注释即可
> 
> ```python
>     "messages": [
>     {"role": "system", "content": "You are a helpful assistant."},
>     {"role": "user", "content": [
>         {"type": "image", "text": "/mnt/pfs/share/Qwen2-VL-7B-Instruct/6803275.png"},
>         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
>     ]}
>     ]
> ```



> > 其实是支持的
> > > @yangxin60-tal 您好，您似乎使用的是vllm openai api server，这个目前是严格按照openai api接口规则处理的，因此不能使用"image"属性，必须使用"image_url"格式。
> > 
> > 
> > 支持的，你将图片的base64得到（即base64_string），按以下格式请求即可：
> > ```
> > "messages": [
> >     {"role": "system", "content": "You are a helpful assistant."},
> >     {"role": "user", "content": [
> >         {"type": "image_url", "image_url": {"url":f"data:image,{base64_string}"}},
> >         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
> >     ]}
> > ```
> 
> 再麻烦一些的话，可以修改vllm的底层代码： 修改1. /****/python3.10/site-packages/vllm/entrypoints/chat_utils.py
> 
> ```python
> def _parse_chat_message_content_parts(
>     role: str,
>     parts: Iterable[ChatCompletionContentPartParam],
>     mm_tracker: BaseMultiModalItemTracker,
> ) -> List[ConversationMessage]:
>     texts: List[str] = []
> 
>     mm_parser = mm_tracker.create_parser()
> 
>     for part in parts:
>         part_type = part["type"]
>         if part_type == "text":
>             text = _TextParser(part)["text"]
>             texts.append(text)
>         elif part_type == "image_url":
>             image_url = _ImageParser(part)["image_url"]
> 
>             if image_url.get("detail", "auto") != "auto":
>                 logger.warning(
>                     "'image_url.detail' is currently not supported and "
>                     "will be ignored.")
> 
>             mm_parser.parse_image(image_url["url"])
> 
> 
>         # elif part_type == "image":
>         #     image = _TextParser(part)["text"]
>         #     mm_parser.parse_image(image)
> 
> 
>         elif part_type == "audio_url":
>             audio_url = _AudioParser(part)["audio_url"]
> 
>             mm_parser.parse_audio(audio_url["url"])
>         elif part_type == "refusal":
>             text = _RefusalParser(part)["refusal"]
>             texts.append(text)
>         else:
>             raise NotImplementedError(f"Unknown part type: {part_type}")
> 
>     text_prompt = "\n".join(texts)
>     mm_placeholder_counts = mm_parser.mm_placeholder_counts()
>     if mm_placeholder_counts:
>         text_prompt = _get_full_multimodal_text_prompt(mm_placeholder_counts,
>                                                        text_prompt)
> 
>     return [ConversationMessage(role=role, content=text_prompt)]
> ```
> 
> 注释部分是需要添加的代码，去掉注释即可
> 
> 修改2. /****/python3.10/site-packages/vllm/multimodal/utils.py
> 
> ```python
> # import base64
> # import os
> # def image_to_base64(image_path):
> #     with open(image_path, "rb") as image_file:
> #         # 读取图片文件并将其编码为Base64
> #         encoded_string = base64.b64encode(image_file.read())
> #         # 将字节类型的Base64编码转换为字符串
> #         encoded_string = encoded_string.decode('utf-8')
> #     return encoded_string
> 
> async def async_fetch_image(image_url: str,
>                             *,
>                             image_mode: str = "RGB") -> Image.Image:
>     """
>     Asynchronously load a PIL image from a HTTP or base64 data URL.
> 
>     By default, the image is converted into RGB format.
>     """
>     if image_url.startswith('http'):
>         image_raw = await global_http_connection.async_get_bytes(
>             image_url, timeout=VLLM_IMAGE_FETCH_TIMEOUT)
>         image = _load_image_from_bytes(image_raw)
> 
>     elif image_url.startswith('data:image'):
>         image = _load_image_from_data_url(image_url)
>     # elif os.path.exists(image_url):
>     #     image_base64 = image_to_base64(image_url)
>     #     image = load_image_from_base64(image_base64)
>     else:
>         raise ValueError("Invalid 'image_url': A valid 'image_url' must start "
>                          "with either 'data:image' or 'http'.")
> 
>     return image.convert(image_mode)
> ```
> 
> 注释部分是需要添加的代码，去掉注释即可
> 
> ```python
>     "messages": [
>     {"role": "system", "content": "You are a helpful assistant."},
>     {"role": "user", "content": [
>         {"type": "image", "text": "/mnt/pfs/share/Qwen2-VL-7B-Instruct/6803275.png"},
>         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
>     ]}
>     ]
> ```
修改1和2都需要吗 还是只需要修改其中一个即可

**Comment by jiezhangGt** [comment]
> > > 其实是支持的
> > > > @yangxin60-tal 您好，您似乎使用的是vllm openai api server，这个目前是严格按照openai api接口规则处理的，因此不能使用"image"属性，必须使用"image_url"格式。
> > > 
> > > 
> > > 支持的，你将图片的base64得到（即base64_string），按以下格式请求即可：
> > > ```
> > > "messages": [
> > >     {"role": "system", "content": "You are a helpful assistant."},
> > >     {"role": "user", "content": [
> > >         {"type": "image_url", "image_url": {"url":f"data:image,{base64_string}"}},
> > >         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
> > >     ]}
> > > ```
> > 
> > 
> > 再麻烦一些的话，可以修改vllm的底层代码： 修改1. /****/python3.10/site-packages/vllm/entrypoints/chat_utils.py
> > ```python
> > def _parse_chat_message_content_parts(
> >     role: str,
> >     parts: Iterable[ChatCompletionContentPartParam],
> >     mm_tracker: BaseMultiModalItemTracker,
> > ) -> List[ConversationMessage]:
> >     texts: List[str] = []
> > 
> >     mm_parser = mm_tracker.create_parser()
> > 
> >     for part in parts:
> >         part_type = part["type"]
> >         if part_type == "text":
> >             text = _TextParser(part)["text"]
> >             texts.append(text)
> >         elif part_type == "image_url":
> >             image_url = _ImageParser(part)["image_url"]
> > 
> >             if image_url.get("detail", "auto") != "auto":
> >                 logger.warning(
> >                     "'image_url.detail' is currently not supported and "
> >                     "will be ignored.")
> > 
> >             mm_parser.parse_image(image_url["url"])
> > 
> > 
> >         # elif part_type == "image":
> >         #     image = _TextParser(part)["text"]
> >         #     mm_parser.parse_image(image)
> > 
> > 
> >         elif part_type == "audio_url":
> >             audio_url = _AudioParser(part)["audio_url"]
> > 
> >             mm_parser.parse_audio(audio_url["url"])
> >         elif part_type == "refusal":
> >             text = _RefusalParser(part)["refusal"]
> >             texts.append(text)
> >         else:
> >             raise NotImplementedError(f"Unknown part type: {part_type}")
> > 
> >     text_prompt = "\n".join(texts)
> >     mm_placeholder_counts = mm_parser.mm_placeholder_counts()
> >     if mm_placeholder_counts:
> >         text_prompt = _get_full_multimodal_text_prompt(mm_placeholder_counts,
> >                                                        text_prompt)
> > 
> >     return [ConversationMessage(role=role, content=text_prompt)]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注释部分是需要添加的代码，去掉注释即可
> > 修改2. /****/python3.10/site-packages/vllm/multimodal/utils.py
> > ```python
> > # import base64
> > # import os
> > # def image_to_base64(image_path):
> > #     with open(image_path, "rb") as image_file:
> > #         # 读取图片文件并将其编码为Base64
> > #         encoded_string = base64.b64encode(image_file.read())
> > #         # 将字节类型的Base64编码转换为字符串
> > #         encoded_string = encoded_string.decode('utf-8')
> > #     return encoded_string
> > 
> > async def async_fetch_image(image_url: str,
> >                             *,
> >                             image_mode: str = "RGB") -> Image.Image:
> >     """
> >     Asynchronously load a PIL image from a HTTP or base64 data URL.
> > 
> >     By default, the image is converted into RGB format.
> >     """
> >     if image_url.startswith('http'):
> >         image_raw = await global_http_connection.async_get_bytes(
> >             image_url, timeout=VLLM_IMAGE_FETCH_TIMEOUT)
> >         image = _load_image_from_bytes(image_raw)
> > 
> >     elif image_url.startswith('data:image'):
> >         image = _load_image_from_data_url(image_url)
> >     # elif os.path.exists(image_url):
> >     #     image_base64 = image_to_base64(image_url)
> >     #     image = load_image_from_base64(image_base64)
> >     else:
> >         raise ValueError("Invalid 'image_url': A valid 'image_url' must start "
> >                          "with either 'data:image' or 'http'.")
> > 
> >     return image.convert(image_mode)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注释部分是需要添加的代码，去掉注释即可
> > ```python
> >     "messages": [
> >     {"role": "system", "content": "You are a helpful assistant."},
> >     {"role": "user", "content": [
> >         {"type": "image", "text": "/mnt/pfs/share/Qwen2-VL-7B-Instruct/6803275.png"},
> >         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
> >     ]}
> >     ]
> > ```
> 
> > > 其实是支持的
> > > > @yangxin60-tal 您好，您似乎使用的是vllm openai api server，这个目前是严格按照openai api接口规则处理的，因此不能使用"image"属性，必须使用"image_url"格式。
> > > 
> > > 
> > > 支持的，你将图片的base64得到（即base64_string），按以下格式请求即可：
> > > ```
> > > "messages": [
> > >     {"role": "system", "content": "You are a helpful assistant."},
> > >     {"role": "user", "content": [
> > >         {"type": "image_url", "image_url": {"url":f"data:image,{base64_string}"}},
> > >         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
> > >     ]}
> > > ```
> > 
> > 
> > 再麻烦一些的话，可以修改vllm的底层代码： 修改1. /****/python3.10/site-packages/vllm/entrypoints/chat_utils.py
> > ```python
> > def _parse_chat_message_content_parts(
> >     role: str,
> >     parts: Iterable[ChatCompletionContentPartParam],
> >     mm_tracker: BaseMultiModalItemTracker,
> > ) -> List[ConversationMessage]:
> >     texts: List[str] = []
> > 
> >     mm_parser = mm_tracker.create_parser()
> > 
> >     for part in parts:
> >         part_type = part["type"]
> >         if part_type == "text":
> >             text = _TextParser(part)["text"]
> >             texts.append(text)
> >         elif part_type == "image_url":
> >             image_url = _ImageParser(part)["image_url"]
> > 
> >             if image_url.get("detail", "auto") != "auto":
> >                 logger.warning(
> >                     "'image_url.detail' is currently not supported and "
> >                     "will be ignored.")
> > 
> >             mm_parser.parse_image(image_url["url"])
> > 
> > 
> >         # elif part_type == "image":
> >         #     image = _TextParser(part)["text"]
> >         #     mm_parser.parse_image(image)
> > 
> > 
> >         elif part_type == "audio_url":
> >             audio_url = _AudioParser(part)["audio_url"]
> > 
> >             mm_parser.parse_audio(audio_url["url"])
> >         elif part_type == "refusal":
> >             text = _RefusalParser(part)["refusal"]
> >             texts.append(text)
> >         else:
> >             raise NotImplementedError(f"Unknown part type: {part_type}")
> > 
> >     text_prompt = "\n".join(texts)
> >     mm_placeholder_counts = mm_parser.mm_placeholder_counts()
> >     if mm_placeholder_counts:
> >         text_prompt = _get_full_multimodal_text_prompt(mm_placeholder_counts,
> >                                                        text_prompt)
> > 
> >     return [ConversationMessage(role=role, content=text_prompt)]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注释部分是需要添加的代码，去掉注释即可
> > 修改2. /****/python3.10/site-packages/vllm/multimodal/utils.py
> > ```python
> > # import base64
> > # import os
> > # def image_to_base64(image_path):
> > #     with open(image_path, "rb") as image_file:
> > #         # 读取图片文件并将其编码为Base64
> > #         encoded_string = base64.b64encode(image_file.read())
> > #         # 将字节类型的Base64编码转换为字符串
> > #         encoded_string = encoded_string.decode('utf-8')
> > #     return encoded_string
> > 
> > async def async_fetch_image(image_url: str,
> >                             *,
> >                             image_mode: str = "RGB") -> Image.Image:
> >     """
> >     Asynchronously load a PIL image from a HTTP or base64 data URL.
> > 
> >     By default, the image is converted into RGB format.
> >     """
> >     if image_url.startswith('http'):
> >         image_raw = await global_http_connection.async_get_bytes(
> >             image_url, timeout=VLLM_IMAGE_FETCH_TIMEOUT)
> >         image = _load_image_from_bytes(image_raw)
> > 
> >     elif image_url.startswith('data:image'):
> >         image = _load_image_from_data_url(image_url)
> >     # elif os.path.exists(image_url):
> >     #     image_base64 = image_to_base64(image_url)
> >     #     image = load_image_from_base64(image_base64)
> >     else:
> >         raise ValueError("Invalid 'image_url': A valid 'image_url' must start "
> >                          "with either 'data:image' or 'http'.")
> > 
> >     return image.convert(image_mode)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注释部分是需要添加的代码，去掉注释即可
> > ```python
> >     "messages": [
> >     {"role": "system", "content": "You are a helpful assistant."},
> >     {"role": "user", "content": [
> >         {"type": "image", "text": "/mnt/pfs/share/Qwen2-VL-7B-Instruct/6803275.png"},
> >         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
> >     ]}
> >     ]
> > ```
> 
> 修改1和2都需要吗 还是只需要修改其中一个即可

都需要

**Comment by jiezhangGt** [comment]
![image](https://github.com/user-attachments/assets/85d237d0-a14b-435a-b54d-85f2cb330053)

**Comment by fyabc** [comment]
> 其实是支持的
> 
> > @yangxin60-tal 您好，您似乎使用的是vllm openai api server，这个目前是严格按照openai api接口规则处理的，因此不能使用"image"属性，必须使用"image_url"格式。
> 
> 支持的，你将图片的base64得到（即base64_string），按以下格式请求即可：
> 
> ```
> "messages": [
>     {"role": "system", "content": "You are a helpful assistant."},
>     {"role": "user", "content": [
>         {"type": "image_url", "image_url": {"url":f"data:image,{base64_string}"}},
>         {"type": "text", "text": "请对图中的内容做OCR识别，不要无中生有，也不要漏掉内容，如果图中存在括号而且括号内没有内容的时候，不要把答案填进去"}
>     ]}
> ```

@jiezhangGt 您好，非常感谢您的说明！这里的方法都是可以的，目前vllm openai api server主要支持url和base64两种格式。

**Comment by bank010** [comment]
> ![image](https://private-user-images.githubusercontent.com/42362818/367226022-85d237d0-a14b-435a-b54d-85f2cb330053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjQ3MjUsIm5iZiI6MTcyNzE2NDQyNSwicGF0aCI6Ii80MjM2MjgxOC8zNjcyMjYwMjItODVkMjM3ZDAtYTE0Yi00MzVhLWI1NGQtODVmMmNiMzMwMDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA3NTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNWRhYTA4NDY2NDVmNzc2NGY1NDkxNzU1MGVhOWJhMzcxY2MwNzE1YjQ4ZWY3ZmYxMzZmMWNmNmRkMTA3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zpbCutCJyZZP30ZWXU4Bu6HTVYV_M0gbbbAObT1vNR8)

你好，我通过这种方法去推理，却发现报错，可以帮我看看吗，用url的方式没有问题
curl http://120.48.69.108:5001/v1/chat/completions     -H "Content-Type: application/json"     -d '{ "model": "Qwen2-VL-7B-Instruct",  "stream":1, "messages": [ {"role": "user", "content": [{"type": "image", "text": "/data1/MLLM/Qwen2-VL/test/20240622163216.png"}, {"type": "text", "text": "What is the text in the illustrate?"}  ]} ] }'

**Comment by bank010** [comment]
> ![image](https://private-user-images.githubusercontent.com/42362818/367226022-85d237d0-a14b-435a-b54d-85f2cb330053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjQ3MjUsIm5iZiI6MTcyNzE2NDQyNSwicGF0aCI6Ii80MjM2MjgxOC8zNjcyMjYwMjItODVkMjM3ZDAtYTE0Yi00MzVhLWI1NGQtODVmMmNiMzMwMDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA3NTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNWRhYTA4NDY2NDVmNzc2NGY1NDkxNzU1MGVhOWJhMzcxY2MwNzE1YjQ4ZWY3ZmYxMzZmMWNmNmRkMTA3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zpbCutCJyZZP30ZWXU4Bu6HTVYV_M0gbbbAObT1vNR8)

你好，我通过您写的例子去推理，发现有些问题，可以帮我看看吗？通过image_url的方式没有问题
curl http://127.0.0.1:5001/v1/chat/completions     -H "Content-Type: application/json"     -d '{ "model": "Qwen2-VL-7B-Instruct",  "stream":1, "messages": [ {"role": "user", "content": [{"type": "image", "text": "/data1/MLLM/Qwen2-VL/test/20240622163216.png"}, {"type": "text", "text": "What is the text in the illustrate?"}  ]} ] }'

**Comment by yangxin60-tal** [comment]
&nbsp;什么问题？
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Sep 24, 2024 04:24 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [QwenLM/Qwen2-VL] qwen2-vl-7B-instruct输入类型为"image"时,报"Unknown part type: image"错误 (Issue #174)

&nbsp;



  

  
你好，我通过您写的例子去推理，发现有些问题，可以帮我看看吗？通过image_url的方式没有问题
 curl http://127.0.0.1:5001/v1/chat/completions     -H "Content-Type: application/json"     -d '{ "model": "Qwen2-VL-7B-Instruct",  "stream":1, "messages": [ {"role": "user", "content": [{"type": "image", "text": "/data1/MLLM/Qwen2-VL/test/20240622163216.png"}, {"type": "text", "text": "What is the text in the illustrate?"}  ]} ] }'
