### ISSUE TITLE
Model Qwen2VLForConditionalGeneration does not support LoRA

### ISSUE THREAD

**Issue by jelly-Ding** [QwenLM/Qwen2-VL#179]
您好，我使用LLaMA-Factory基于Qwen2-VL-7B-Instruct-GPTQ-Int8训练了一个qlora，当使用transformers作为后端时一切正常，但速度较慢，所以我尝试使用vllm部署，但遇到了ValueError: Model Qwen2VLForConditionalGeneration does not support LoRA, but LoRA is enabled.的问题，请问如何解决或后续有相关计划吗
我拉取了最新的add_qwen2_vl_new分支，单独部署Qwen2-VL-7B-Instruct-GPTQ-Int8是正常的
vllm服务启动命令为：
vllm serve /path/to/Qwen2-VL-7B-Instruct-GPTQ-Int8  --enable-lora --lora-modules lora1=/path/to/lora

**Comment by fyabc** [comment]
@jelly-Ding 您好，目前Qwen2-VL的vLLM模型部署暂时不支持载入lora。该功能正在开发中，目前您可以将lora参数合并进模型之后正常部署。

**Comment by jelly-Ding** [comment]
通过修改vllm的[qwen2_vl.py](https://github.com/fyabc/vllm/blob/add_qwen2_vl_new/vllm/model_executor/models/qwen2_vl.py)，仿照qwen2.py增加了对lora的支持。感谢

**Comment by fyabc** [comment]
> 通过修改vllm的[qwen2_vl.py](https://github.com/fyabc/vllm/blob/add_qwen2_vl_new/vllm/model_executor/models/qwen2_vl.py)，仿照qwen2.py增加了对lora的支持。感谢

感谢您的反馈！我们会尽快测试lora支持并更新相关代码。

**Comment by zzf2grx** [comment]
> > 通过修改vllm的[qwen2_vl.py](https://github.com/fyabc/vllm/blob/add_qwen2_vl_new/vllm/model_executor/models/qwen2_vl.py)，仿照qwen2.py增加了对lora的支持。感谢
> 
> 感谢您的反馈！我们会尽快测试lora支持并更新相关代码。

请问vllm中什么时候会支持加载lora呀？以及awq等量化模型是否也可以支持加载lora？

**Comment by zzf2grx** [comment]
> 通过修改vllm的[qwen2_vl.py](https://github.com/fyabc/vllm/blob/add_qwen2_vl_new/vllm/model_executor/models/qwen2_vl.py)，仿照qwen2.py增加了对lora的支持。感谢

请问可以分享下加载lora的代码吗？

**Comment by evilbear** [comment]
> > 通过修改vllm的[qwen2_vl.py](https://github.com/fyabc/vllm/blob/add_qwen2_vl_new/vllm/model_executor/models/qwen2_vl.py)，仿照qwen2.py增加了对lora的支持。感谢
> 
> 请问可以分享下加载lora的代码吗？

我也有多lora部署和需求，尝试修改qwen2_vl.py生效了
1. 版本 vllm==0.6.3.post1  transformers==4.46.1
2. 我的cona环境是/data2/xiongyz/envs/tender-html-llm， 你需要替换你的对应路径下qwen2_vl.py文件
/data2/xiongyz/envs/tender-html-llm/lib/python3.11/site-packages/vllm/model_executor/models/qwen2_vl.py
3. 记得先备份下原始文件，替换后在我的环境下直接生效

[qwen2_vl.py.txt](https://github.com/user-attachments/files/17630307/qwen2_vl.py.txt)

**Comment by Road2Redemption** [comment]
@fyabc 请问现在支持直接使用lora了吗？我在使用llamafactory和qwen2vl的本地推理脚本
