### ISSUE TITLE
Why video is always "error"? 阿里工程师是都裁完了吗？好歹是大厂

### ISSUE THREAD

**Issue by glennchina** [QwenLM/Qwen2-VL#192]
HF MS Qwen2-VL-72B video始终报错。
自测过没有？有点大厂的样子吧

**Comment by Note-Liu** [comment]
I meet the same :Error when inputing a video.

**Comment by glennchina** [comment]
The issue isn't fixed yet.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Note-Liu ***@***.***>
发送时间: Friday, September 13, 2024 10:22:37 AM
收件人: QwenLM/Qwen2-VL ***@***.***>
抄送: Gary ***@***.***>; State change ***@***.***>
主题: Re: [QwenLM/Qwen2-VL] Why video is always "error"? 阿里工程师是都裁完了吗？好歹是大厂 (Issue #192)


I meet the same :Error when inputing a video.

―
