### ISSUE TITLE
如何使qwen2-vl支持128K？

### ISSUE THREAD

**Issue by kelvennn** [QwenLM/Qwen2-VL#193]

**Comment by logicwong** [comment]
你可以直接在config file里设置sliding_window, max_position_embeddings, and model_max_length为128k试试，m-rope可以压缩position id，在我们的测试里长视频支持到80k也还ok，但我们没有做很严谨的长序列测试

**Comment by Leon1207** [comment]
如果是使用这样的方式进行推理，应该如何设置config呢：
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "/mnt/82_store/LLM-weights/Qwen2-VL-72B-Instruct",
    torch_dtype=torch.bfloat16,
    attn_implementation="flash_attention_2",
    device_map="auto",
)
