### ISSUE TITLE
有支持Vllm并且在上面运行量化模型的计划吗？

### ISSUE THREAD

**Issue by wciq1208** [QwenLM/Qwen2-VL#20]

**Comment by seasoncool** [comment]
同問 +1

**Comment by chensiye-csy** [comment]
refer 
https://github.com/vllm-project/vllm/pull/7905

**Comment by fyabc** [comment]
@seasoncool @wciq1208 您好，vLLM代码已更新，目前最新版已支持Qwen2-VL-*B-Instruct-AWQ模型的推理。
对于GPTQ量化模型，正在修复模型文件中的一些小bug，预计很快也可支持。

**Comment by wciq1208** [comment]
> @seasoncool @wciq1208 您好，vLLM代码已更新，目前最新版已支持Qwen2-VL-*B-Instruct-AWQ模型的推理。 对于GPTQ量化模型，正在修复模型文件中的一些小bug，预计很快也可支持。

感谢！坐等合入

**Comment by kq-chen** [comment]
The checkpoints for the Qwen2-VL-*B-Instruct-GPTQ-Int{4,8} series models have been updated. The new version of the GPTQ checkpoints is expected to be compatible with the updated forked [vLLM](https://github.com/fyabc/vllm/tree/add_qwen2_vl_new) for execution.
