### ISSUE TITLE
What's the max context length of qwen2-vl

### ISSUE THREAD

**Issue by gaoxt1983** [QwenLM/Qwen2-VL#200]
I am new to VL model. I want to know whether there is a way to know context length of a VL model?

**Comment by fyabc** [comment]
@gaoxt1983 Hi, currently, the default context length of Qwen2-VL is 32768, specified by `max_position_embeddings` in [`config.json`](https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct/blob/main/config.json#L17).

**Comment by Fujiaoji** [comment]
> [@gaoxt1983](https://github.com/gaoxt1983) Hi, currently the default context length of Qwen2-VL is 32768, specified by `max_position_embeddings` in [`config.json`](https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct/blob/main/config.json#L17).

Really, because the input token length is around 10000 will cause the error. Maybe a different number?
