### ISSUE TITLE
warning:Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section'}

### ISSUE THREAD

**Issue by AIFFFENG** [QwenLM/Qwen2-VL#209]
这个有影响吗

**Comment by fyabc** [comment]
@AIFFFENG 您好，这个是[一个已知bug](https://github.com/huggingface/transformers/issues/33401)，请参考readme中的说明，安装正确的transformers版本。

**Comment by leonbadboy** [comment]
vllm 0.62 运行还是报这个错：Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section'}
