### ISSUE TITLE
LLamafactory微调后模型读取问题

### ISSUE THREAD

**Issue by Titor99** [QwenLM/Qwen2-VL#216]
在测试Qwen2-VL在llamafactory微调训练（finetune）后的模型时，会出现

Traceback (most recent call last):
  File "/data/wlw/Qwen2-VL/test.py", line 41, in <module>
    text = processor.apply_chat_template(
  File "/usr/local/lib/python3.10/site-packages/transformers/processing_utils.py", line 988, in apply_chat_template
    raise ValueError(
ValueError: No chat template is set for this processor. Please either set the `chat_template` attribute, or provide a chat template as an argument. See https://huggingface.co/docs/transformers/main/en/chat_templating for more information.

原来的预训练模型都没问题，在读取微调后llamafactory中save的模型文件就会报错，设置好chat_template后也会出现

RuntimeError: shape mismatch: value tensor of shape [24, 3584] cannot be broadcast to indexing result of shape [0, 3584]

问题，求解决方案。

**Comment by Titor99** [comment]
> 试试复制预训练模型中的chat_template.json 到模型文件夹下。

哦哦哦，确实复制一下就解决了，感谢大佬！

**Comment by gxlover0625** [comment]
https://github.com/hiyouga/LLaMA-Factory/pull/5857，我有同样的bug，提交了issue，目前已经被修改，且支持多阶段微调

**Comment by Cannot-learn-much** [comment]
请问解决了吗，我也是每次都会遇到RuntimeError: shape mismatch: value tensor of shape [24, 3584] cannot be broadcast to indexing result of shape [0, 3584]
