### ISSUE TITLE
Typo in doc example

### ISSUE THREAD

**Issue by PaulWongDlut** [QwenLM/Qwen2-VL#222]
"Start an OpenAI API Service"

python demo:
'model="Qwen2-7B-Instruct"' -> 'model="Qwen2-VL-7B-Instruct"'

the typo leads to error below:

openai.NotFoundError: Error code: 404 - {'object': 'error', 'message': 'The model `Qwen2-7B-Instruct` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404}

**Comment by ddemillard** [comment]
Thank you Paul, saved me some time!

**Comment by kq-chen** [comment]
Since the [commit](https://github.com/QwenLM/Qwen2-VL/commit/46b5a0e0031a345596fe75bce34f11dbf877b6cc) has resolved the issue, I am going to close the issue.
