### ISSUE TITLE
请问PP把VIT和部分LLM layer分到一起，剩下的layers平分，这种切法当某些数据中图像太大或者视频帧数太多，会不会导致 负载不均衡？

### ISSUE THREAD

**Issue by ghoshaw** [QwenLM/Qwen2-VL#240]
如题。 如果某个batch中图像很大，或者视频很长，VIT的计算量会不会明显超出其他stage的文本计算量，从而导致PP的空泡更大？有没有什么解决方案？ 谢谢

**Comment by logicwong** [comment]
其实还好

1. 我们在训练前把样本打包成某个长度（例如8K）的序列，在LLM layer里的计算量是一致的；
2. 每个序列里的样本数量不固定（图像大了样本就少些，图像小了样本就多些），因此vit的计算量也差不多；
3. 注意到，我们的vit本身不大只有600+M，对于72B或7B规模都算比较小的。
