### ISSUE TITLE
多图离线推理和vllm部署推理显存占用差距大

### ISSUE THREAD

**Issue by AlphaNext** [QwenLM/Qwen2-VL#242]
7B的模型，多图离线推理时：显存最高不到25000MB，vllm部署时：显存直接60000MB了，差了两倍多，是哪块的原因引起的呢？

**Comment by verigle** [comment]
请问vllm 部署qwen2-vl支持多图片同时处理了吗

**Comment by sunway86** [comment]
启动加参数 --limit-mm-per-prompt image
