### ISSUE TITLE
论文中为什么举例说224x224的图像经过ViT之后，得到66个视觉token呢？

### ISSUE THREAD

**Issue by Xiaolong-RRL** [QwenLM/Qwen2-VL#245]
如下图所示：
![image](https://github.com/user-attachments/assets/15b59922-11ae-4260-8659-ff28e09dc9d4)

**Comment by xuguohai** [comment]
1、 (224/14) * (224/14) = 16 * 16
2、相邻2*2 token 通过MLP merge:  8 * 8 = 64
3、开头和结束各加一个speical token: 64 + 2 =66

**Comment by Xiaolong-RRL** [comment]
明白了，漏掉了两个special token，感谢大佬！！
