### ISSUE TITLE
RuntimeError: CUDA Error: Device-Side Assert Triggered

### ISSUE THREAD

**Issue by dongZheX** [QwenLM/Qwen2-VL#26]
I run QWen2-VL-7B-Instruct in 
+ A800-80G, 
+ use flash-attention-v2,
+ torch-version == 2.4
+ cuda_version == 12.2
+ qwen-utils

The infer code is same as these you have provided in huggingface model-card. 

When I request some cases, the model will report error "RuntimeError: CUDA Error: Device-Side Assert Triggered"

The image size is 150 × 29.

Could you give any ideas to solve this?

**Comment by dongZheX** [comment]
It looks to happen when process litter image or multi image.

This image have same problem: 

https://datasets-server.huggingface.co/cached-assets/MMMU/MMMU/--/694fe284ef3349ee16d335b8120dbbfdd8ef2cee/--/Pharmacy/validation/5/image_1/image.png?Expires=1725003218&Signature=XnEt5oiY9ITUNw2btH5-s9Psx9OKR2gVesoeWrlfmOqpKqAMAcKeTy7QPDKFMltREWMFR5UniAtu0EkCGdAWgGkimxs~NHUjybj6k9OUFCJ-B6z0OvPemMm6FwECvTHjfucUYlBF3pQOrXh8zQhtc4-E4S6mImcJMsFxCqYK8FGQ4gZZtYzxE3Ja76~iv6OlXI8BXf01WZ3hLcgfqctjbu44-f9hMoqWVhiZ0CFYTZcgAL656C-~stRVuonBv~d5ll98P7kT-8sLeatevXGhp9K3kyA5Gllq~KxWquInkMIdUZms~KTa9MNiSUUn6h-p34jZRn~emy9qYGPJ09RIuA__&Key-Pair-Id=K3EI6M078Z3AC3

**Comment by dongZheX** [comment]
This bug may be caused by flashattention, if i don't use flashattention, everything is ok.

**Comment by simonJJJ** [comment]
@dongZheX Can you provide an unexpired image url?

**Comment by dongZheX** [comment]
> @dongZheX Can you provide an unexpired image url?

any image , width or heigh < 56

**Comment by dongZheX** [comment]
> @dongZheX Can you provide an unexpired image url?

rotary_seq_len = cache_position[-1] + 10

**Comment by dongZheX** [comment]
https://github.com/huggingface/transformers/pull/33161
