### ISSUE TITLE
[ERROR] safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by jjjlyn** [QwenLM/Qwen2-VL#264]
Hi there :) 

```
File "/workspace/vllm/vllm-venv/lib/python3.10/site-packages/vllm/model_executor/model_loader/weight_utils.py", line 406, in safetensors_weights_iterator
    with safe_open(st_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
```

When executing `https://huggingface.co/Qwen/Qwen2-VL-72B-Instruct-AWQ` model on **vllm**, it invokes error.

This is my command below:
```sh
VLLM_WORKER_MULTIPROC_METHOD=spawn python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-VL-72B-Instruct-AWQ --model /workspace/Qwen2-VL-72B-Instruct-AWQ/ --disable-custom-all-reduce --tensor-parallel-size 2 --gpu-memory-utilization 0.8 --max-model-len 14000 --port 50000
```

### Environment
- NVIDIA RTX3090 * 2

**Comment by rahulvk007** [comment]
I am also having the same issue.

Command used:
```
vllm serve Qwen/Qwen2-VL-72B-Instruct-AWQ
```

**Comment by kq-chen** [comment]
sorry, it seems that the file `model-00001-of-00011.safetensors` got corrupted during the uploading. I will update the file as soon as possible.

**Comment by kq-chen** [comment]
fixed [here](https://huggingface.co/Qwen/Qwen2-VL-72B-Instruct-AWQ/commit/712d5a5a210e7f0af603d2a949b577c68de2c6ef)! please try again!

**Comment by jjjlyn** [comment]
Thanks a lot :)

**Comment by azuercici** [comment]
I have met the same mistake when loading Qwen2-VL-7B-Instruct，is there the same problem with safesensor file？
