### ISSUE TITLE
连接是否变了，下载安装不了

### ISSUE THREAD

**Issue by cqray1990** [QwenLM/Qwen2-VL#268]
pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830 accelerate

**Comment by kq-chen** [comment]
It's probably a network issue; you can try downloading using domestic sources. refer #41 

```bash
pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830 accelerate -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
```
