### ISSUE TITLE
指标不对齐是什么原因呢

### ISSUE THREAD

**Issue by luyao-cv** [QwenLM/Qwen2-VL#27]
您好，我使用[VLMEvalkit](https://github.com/kq-chen/VLMEvalKit/tree/add_qwen2vl) 工具，测出来的分数相差较大，请问是什么原因呢？

模型 | docvqa-val | chartqa | infovqa-val | textvqa | ocrbench
-- | -- | -- | -- | -- | --
测试工具 | val: VLMEvalKit | VLMEvalKit | VLMEvalKit | VLMEvalKit | VLMEvalKit
qwen2 vl | 89.262  VLMEvalKit | 72.6 VLMEvalKit | 64.1 | 79.2 | 780
qwen2 vl github | 88.34test: 90.1 | 73.5 | 65.5 | 79.7 | 794

我的环境：
cuda 11.8
python: 3.10.14 
transformers: 4.45.0.dev0
flash-attn: 2.6.3
pytorch: 2.4.0

**Comment by nemonameless** [comment]
@kq-chen @ShuaiBai623 
how to get the accurate indicators? thanks

**Comment by luyao-cv** [comment]
qwen2 vl 2B | 89.262  VLMEvalKit | 72.6 VLMEvalKit | 64.1 | 79.2 | 794(# ocrbench min_pixels=1280*14*14, max_pixels=5120*56*56)
-- | -- | -- | -- | -- | --
qwen2 vl 2B github | 88.34test: 90.1 | 73.5 | 65.5 | 79.7 | 794
qwen2 vl 7B | 93.8 | 83.6 | 76.1 | 84.4 | 840
qwen2 vl 7B github | val: 93.89test: 94.5 | 83.0 | 76.5 | 84.3 | 845




2B 和 7B都对不上，其中2Bocrbench 我调整了下参数，能够复现出794的精度，其他的都没法复线，请问这个可能是什么原因呢？希望作者更新的权重能给出脚本参数和最新一次测试的精度，这样我们方便对齐精度，感谢。

**Comment by logicwong** [comment]
另外github里报的是infovqa test的结果，不是val的结果。2B模型我们内部测infovqa val就是64.2

**Comment by luyao-cv** [comment]
> > 模型	docvqa-val	chartqa	infovqa-val	textvqa	ocrbench
> > 测试工具	val: VLMEvalKittest	VLMEvalKittest	VLMEvalKit	VLMEvalKit	VLMEvalKit
> > qwen2 vl 2B	89.262 VLMEvalKit	72.6 VLMEvalKit	64.1	79.2	794(# ocrbench min_pixels=1280_14_14, max_pixels=5120_56_56)
> > qwen2 vl 2B github	88.34test: 90.1	73.5	65.5	79.7	794
> > qwen2 vl 7B	93.8	83.6	76.1	84.4	840
> > qwen2 vl 7B github	val: 93.89test: 94.5	83.0	76.5	84.3	845
> > 2B 和 7B都对不上，其中2Bocrbench 我调整了下参数，能够复现出794的精度，其他的都没法复现，请问这个可能是什么原因呢？希望作者更新的权重能给出脚本参数和最新一次测试的精度，这样我们方便对齐精度，感谢。
> 
> 查出代码还有点diff，我们内部评测时用的是vllm，两边有一些细微的差别。现在正在对齐代码，有结果后会及时更新代码。

好的，谢谢。目前新权重跑出来的结果还有一点diff，相差0.几的样子

**Comment by luyao-cv** [comment]
> 另外github里报的是infovqa test的结果，不是val的结果。2B模型我们内部测infovqa val是64.2

好的，谢谢，我测出来是64.18

**Comment by luyao-cv** [comment]
我复现出来是有844，论文866是怎么来的呢？

**Comment by zhudongwork** [comment]
> 我复现出来是有844，论文866是怎么来的呢？

我本地是840，所以很疑惑论文里面的精度是怎么来的，有什么特殊配置吗

**Comment by kq-chen** [comment]
可以使用最新版本的[VLMEvalKit](https://github.com/open-compass/VLMEvalKit)测试，[qwen2_vl/model.py#L71](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/model.py#L71) 这里针对OCRBench设置了min_pixels = 10 * 10 * 28 * 28

**Comment by zhudongwork** [comment]
> @luyao-cv @zhudongwork 可以使用最新版本的[VLMEvalKit](https://github.com/open-compass/VLMEvalKit)测试，[qwen2_vl/model.py#L71](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/model.py#L71) 这里针对OCRBench设置了min_pixels = 10 * 10 * 28 * 28

max_pixels设置多大

**Comment by zhudongwork** [comment]
> > 模型	docvqa-val	chartqa	infovqa-val	textvqa	ocrbench
> > 测试工具	val: VLMEvalKittest	VLMEvalKittest	VLMEvalKit	VLMEvalKit	VLMEvalKit
> > qwen2 vl 2B	89.262 VLMEvalKit	72.6 VLMEvalKit	64.1	79.2	794(# ocrbench min_pixels=1280_14_14, max_pixels=5120_56_56)
> > qwen2 vl 2B github	88.34test: 90.1	73.5	65.5	79.7	794
> > qwen2 vl 7B	93.8	83.6	76.1	84.4	840
> > qwen2 vl 7B github	val: 93.89test: 94.5	83.0	76.5	84.3	845
> > 2B 和 7B都对不上，其中2Bocrbench 我调整了下参数，能够复现出794的精度，其他的都没法复现，请问这个可能是什么原因呢？希望作者更新的权重能给出脚本参数和最新一次测试的精度，这样我们方便对齐精度，感谢。
> 
> 查出代码还有点diff，我们内部评测时用的是vllm，两边有一些细微的差别。现在正在对齐代码，有结果后会及时更新代码。

大佬能给一下vllm的SamplingParams参数不

**Comment by zhudongwork** [comment]
> @luyao-cv @zhudongwork 可以使用最新版本的[VLMEvalKit](https://github.com/open-compass/VLMEvalKit)测试，[qwen2_vl/model.py#L71](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/model.py#L71) 这里针对OCRBench设置了min_pixels = 10 * 10 * 28 * 28

用vllm复刻出来了，本地863。但是不知道官方的vllm配置是啥.
下面是我的配置：
`SamplingParams(
                temperature=0.1,
                top_p=0.001,
                repetition_penalty=1.05,
                max_tokens=256,
                stop_token_ids=[],
            )`

**Comment by nemonameless** [comment]
@kq-chen  请问改后的ocrbench参数是只针对7B的配置吧？别的数据集的min_pixels 是否也有特殊设置呢？还请也更新下吧谢谢

**Comment by kq-chen** [comment]
只有ocrbench的min_pixels设置了`10*10*28*28`，其他bench上的min_pixels都是`1280*28*28`，max_pixels都是`16384*28*28`。具体可以看这里的[config.py](https://github.com/open-compass/VLMEvalKit/blob/9ca28fd06bac52d0c42845dac8891dd9e6354611/vlmeval/config.py#L253-L264)，推理的超参数为
```python
max_new_tokens=2048,
top_p=0.001,
top_k=1,
temperature=0.01,
repetition_penalty=1.0,
```
可以参考[这里](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/model.py#L30-L34)的配置。

**Comment by luyao-cv** [comment]
> @nemonameless
> 
> 2B 7B 72B的模型只有ocrbench的min_pixels设置了`10*10*28*28`，别的数据集的min_pixels都是`1280*28*28`，max_pixels都是`16384*28*28`。具体可以看这里的[config.py](https://github.com/open-compass/VLMEvalKit/blob/9ca28fd06bac52d0c42845dac8891dd9e6354611/vlmeval/config.py#L253-L264)。其他一些数据集上的配置主要是prompt的配置，可以看[prompt.py](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/prompt.py)文件。
> 
> 推理的超参数为
> 
> ```python
> max_new_tokens=2048,
> top_p=0.001,
> top_k=1,
> temperature=0.01,
> repetition_penalty=1.0,
> ```
> 
> 可以参考[这里](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/model.py#L30-L34)的配置。

ocrbench min_pixels设置为 10*10*28*28，7B模型跑出来的分数只有858分。对不上论文的866分。

> stop_token_ids

我跑的只有858

**Comment by zhudongwork** [comment]
> @nemonameless
> 
> 2B 7B 72B的模型只有ocrbench的min_pixels设置了`10*10*28*28`，别的数据集的min_pixels都是`1280*28*28`，max_pixels都是`16384*28*28`。具体可以看这里的[config.py](https://github.com/open-compass/VLMEvalKit/blob/9ca28fd06bac52d0c42845dac8891dd9e6354611/vlmeval/config.py#L253-L264)。其他一些数据集上的配置主要是prompt的配置，可以看[prompt.py](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/prompt.py)文件。
> 
> 推理的超参数为
> 
> ```python
> max_new_tokens=2048,
> top_p=0.001,
> top_k=1,
> temperature=0.01,
> repetition_penalty=1.0,
> ```
> 
> 可以参考[这里](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/model.py#L30-L34)的配置。

用新版的配置参数本地跑出来是865(A100)，但是同等配置下vllm跑出来的结果差距较大，所以还是换成了transformers版本的推理

**Comment by zhudongwork** [comment]
> > > @nemonameless
> > > 2B 7B 72B的模型只有ocrbench的min_pixels设置了`10*10*28*28`，别的数据集的min_pixels都是`1280*28*28`，max_pixels都是`16384*28*28`。具体可以看这里的[config.py](https://github.com/open-compass/VLMEvalKit/blob/9ca28fd06bac52d0c42845dac8891dd9e6354611/vlmeval/config.py#L253-L264)。其他一些数据集上的配置主要是prompt的配置，可以看[prompt.py](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/prompt.py)文件。
> > > 推理的超参数为
> > > ```python
> > > max_new_tokens=2048,
> > > top_p=0.001,
> > > top_k=1,
> > > temperature=0.01,
> > > repetition_penalty=1.0,
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 可以参考[这里](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/model.py#L30-L34)的配置。
> > 
> > 
> > 用新版的配置参数本地跑出来是865(A100)，但是同等配置下vllm跑出来的结果差距较大，所以还是换成了transformers版本的推理
> 
> 请问用了transformers的什么版本呀，我直接git clone ，然后pip install -e.的

pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830 accelerate

**Comment by zhudongwork** [comment]
> > > @nemonameless
> > > 2B 7B 72B的模型只有ocrbench的min_pixels设置了`10*10*28*28`，别的数据集的min_pixels都是`1280*28*28`，max_pixels都是`16384*28*28`。具体可以看这里的[config.py](https://github.com/open-compass/VLMEvalKit/blob/9ca28fd06bac52d0c42845dac8891dd9e6354611/vlmeval/config.py#L253-L264)。其他一些数据集上的配置主要是prompt的配置，可以看[prompt.py](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/prompt.py)文件。
> > > 推理的超参数为
> > > ```python
> > > max_new_tokens=2048,
> > > top_p=0.001,
> > > top_k=1,
> > > temperature=0.01,
> > > repetition_penalty=1.0,
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 可以参考[这里](https://github.com/open-compass/VLMEvalKit/blob/ce866b872205e12bc811f595e5ba43a6af13811a/vlmeval/vlm/qwen2_vl/model.py#L30-L34)的配置。
> > 
> > 
> > 用新版的配置参数本地跑出来是865(A100)，但是同等配置下vllm跑出来的结果差距较大，所以还是换成了transformers版本的推理
> 
> 请问用了transformers的什么版本呀，我直接git clone ，然后pip install -e.的

`pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830`

**Comment by luyao-cv** [comment]
用A100，复现出866的分数了。

**Comment by zhudongwork** [comment]
> 用A100，复现出866的分数了。

MMMU_VAL的分数能复现出来不，我本地只有50

**Comment by chenghuaWang** [comment]
请问qwen2vl官方测试的时候textVQA使用的prompt是什么？

**Comment by yokings** [comment]
> > 用A100，复现出866的分数了。
> 
> MMMU_VAL的分数能复现出来不，我本地只有50

请问复现出来了吗，我本地也只有50.01
