### ISSUE TITLE
Failed to load Qwen2-VL-72B-Instruct-AWQ.

### ISSUE THREAD

**Issue by mind-animator-design** [QwenLM/Qwen2-VL#271]
I encountered an error when loading Qwen2-VL-72B-Instruct-AWQ:
'ImportError: /data1/home/cddu/anaconda3/envs/qwen2-vl-flash-att/lib/python3.10/site-packages/awq_inference_engine.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_dim_IntList4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbNS5_8optionalINS5_10ScalarTypeEEE'

My hardware is an A100 80G, and the virtual environment was set up in the following way:
![1727254342670](https://github.com/user-attachments/assets/536dcb5e-14e8-4693-b8e8-a6901e1be189)

Could you please help me check where the configuration issue might be?

**Comment by kq-chen** [comment]
maybe try install autoawq with `INSTALL_KERNELS=1 pip install git+https://github.com/casper-hansen/AutoAWQ.git` to see if help?

**Comment by kq-chen** [comment]
also, check if #264 is related to your problem?

**Comment by mind-animator-design** [comment]
Thank you, I think the problem might be with the model I downloaded (#264). I'll try re-downloading it and let you know if that solves the issue.

**Comment by mind-animator-design** [comment]
Thank you for your guidance. Installing autoawq with INSTALL_KERNELS=1 pip install git+https://github.com/casper-hansen/AutoAWQ.git solved the problem.
