### ISSUE TITLE
Can we just embedding the image with visual part?

### ISSUE THREAD

**Issue by whyiug** [QwenLM/Qwen2-VL#287]
As the title says. we need to embed the image with visual part separately.

For now , i use the code bellow.
Trouble is, I still loaded all the parameters.
Can you guys give me some tips to simplify the code?

```python
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor, Qwen2VLConfig
from qwen_vl_utils import process_vision_info
import time
import torch

model_name = "Qwen/Qwen2-VL-7B-Instruct"
# model = Qwen2VLForConditionalGeneration.from_pretrained(model_name, torch_dtype="auto", device_map="auto")
model = Qwen2VLForConditionalGeneration.from_pretrained(model_name)
visual_model = model.visual
visual_model.to("cuda")

min_pixels = 100000
max_pixels = 500000
processor = AutoProcessor.from_pretrained(model_name, min_pixels=min_pixels, max_pixels=max_pixels)

IMAGE_PATH = '/home/xxxx.jpeg'
question = "描述这张图片。"
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": IMAGE_PATH,
                'max_pixels': max_pixels,
                'min_pixels': min_pixels,
            },
            {"type": "text", "text": question},
        ],
    }
]

text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)

inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
# inputs = inputs.to("cuda")
inputs = inputs.to("cuda")


pixel_values = inputs["pixel_values"].type(torch.bfloat16)

image_embeds = visual_model(pixel_values, grid_thw=inputs["image_grid_thw"])
print(image_embeds.shape)
```

**Comment by whyiug** [comment]
@simonJJJ @ShuaiBai623 Please have a look and consider it, this is really important for our production environment.

**Comment by Andcircle** [comment]
@whyiug I also need this to use VLLM, interestingly, they only support input with image embeds instead of pixel values

**Comment by whyiug** [comment]
> image embeds

image embedding is enough from vLLM. https://github.com/vllm-project/vllm/pull/8856

**Comment by Andcircle** [comment]
> > image embeds
> 
> image embedding is enough from vLLM. [vllm-project/vllm#8856](https://github.com/vllm-project/vllm/pull/8856)

Is there other way to directly use image instead of embedding? or vllm qwen2-vl only support image imbedding

**Comment by whyiug** [comment]
I solved the problem with a smaller gpu memory. 
I'll post the code in case anyone else runs into a similar problem.

```python
import torch
from transformers import AutoConfig
from transformers import AutoProcessor
from transformers.models.qwen2_vl.modeling_qwen2_vl import (
    Qwen2VisionTransformerPretrainedModel,
)
from safetensors.torch import load_file
from qwen_vl_utils import process_vision_info
import time
import os

visual_model = None
processor = None
device = "cuda"


def load_model():
    global visual_model, processor
    model_path = "/home/work/.cache/modelscope/hub/qwen/Qwen2-VL-7B-Instruct"
    config = AutoConfig.from_pretrained(model_path)
    visual_model = Qwen2VisionTransformerPretrainedModel._from_config(
        config=config.vision_config
    )
    checkpoint_path = os.path.join(model_path, "model-00001-of-00005.safetensors")
    checkpoint = load_file(checkpoint_path)
    visual_weights = {
        key.replace("visual.", ""): value
        for key, value in checkpoint.items()
        if key.startswith("visual.")
    }
    visual_model.load_state_dict(visual_weights, strict=False)
    visual_model.to(device)
    visual_model.eval()
    processor = AutoProcessor.from_pretrained(model_path)


load_model()


def tmp_process_image(image_path, question="", min_pixels=350000, max_pixels=500000):
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": image_path,
                    "max_pixels": max_pixels,
                    "min_pixels": min_pixels,
                },
                {"type": "text", "text": question},
            ],
        }
    ]

    text = processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    image_inputs, video_inputs = process_vision_info(messages)

    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    )
    inputs = inputs.to(device)
    pixel_values = inputs["pixel_values"].type(torch.bfloat16)
    with torch.no_grad():
        image_embeds = visual_model(pixel_values, grid_thw=inputs["image_grid_thw"])
    return inputs["image_grid_thw"], image_embeds


if __name__ == "__main__":
    image_path = "/home/work/data/xxx/up.jpeg"
    print("Processing image...")
    image_grid_thw1, image_embeds1 = tmp_process_image(
        image_path, question="", min_pixels=350000, max_pixels=500000
    )
    print(image_embeds1)
    print("Image processed.")
    time.sleep(1000)

```
<img width="705" alt="image" src="https://github.com/user-attachments/assets/7f76bed9-c4b5-4bbd-87b4-b78561689d47">

**Comment by LianghuiGuo** [comment]
@whyiug amazing work! 
I'm wondering whether we can get text embedding through similar way?

**Comment by whyiug** [comment]
> @whyiug amazing work! I'm wondering whether we can get text embedding through similar way? Do you have a try on it?

没有。感觉只获取 text embedding 是没有意义的，而且这个耗时非常少。如果非要获取，可以查看这里[代码](https://github.com/huggingface/transformers/blob/8a734ea2c340beee23e665601919814918bf4c43/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1683)
我把 visual model 拆开是因为希望图片模型和文本模型分开部署，而且业务需要一图多问，这对延时和吞吐都有提升。
vllm 支持输入图片 embedding 的 PR:  https://github.com/vllm-project/vllm/pull/8856

**Comment by LianghuiGuo** [comment]
> > @whyiug amazing work! I'm wondering whether we can get text embedding through similar way? Do you have a try on it?
> 
> 没有。感觉只获取 text embedding 是没有意义的，而且这个耗时非常少。如果非要获取，可以查看这里[代码](https://github.com/huggingface/transformers/blob/8a734ea2c340beee23e665601919814918bf4c43/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1683) 我把 visual model 拆开是因为希望图片模型和文本模型分开部署，而且业务需要一图多问，这对延时和吞吐都有提升。 vllm 支持输入图片 embedding 的 PR: [vllm-project/vllm#8856](https://github.com/vllm-project/vllm/pull/8856)

好的，感谢！我是在想能不能用图文的embedding来做图文检索任务，不知道是否有可行性。

**Comment by goen-kkk** [comment]
> I solved the problem with a smaller gpu memory. I'll post the code in case anyone else runs into a similar problem. Just look at the`load_model` section.
> 
> ```python
> import torch
> from transformers import AutoConfig
> from transformers import AutoProcessor
> from transformers.models.qwen2_vl.modeling_qwen2_vl import (
>     Qwen2VisionTransformerPretrainedModel,
> )
> from safetensors.torch import load_file
> from qwen_vl_utils import process_vision_info
> import time
> import os
> 
> visual_model = None
> processor = None
> device = "cuda"
> 
> 
> def load_model():
>     global visual_model, processor
>     model_path = "/home/work/.cache/modelscope/hub/qwen/Qwen2-VL-7B-Instruct"
>     config = AutoConfig.from_pretrained(model_path)
>     visual_model = Qwen2VisionTransformerPretrainedModel._from_config(
>         config=config.vision_config
>     )
>     checkpoint_path = os.path.join(model_path, "model-00001-of-00005.safetensors")
>     checkpoint = load_file(checkpoint_path)
>     visual_weights = {
>         key.replace("visual.", ""): value
>         for key, value in checkpoint.items()
>         if key.startswith("visual.")
>     }
>     visual_model.load_state_dict(visual_weights, strict=False)
>     visual_model.to(device)
>     visual_model.eval()
>     processor = AutoProcessor.from_pretrained(model_path)
> 
> 
> load_model()
> 
> 
> def tmp_process_image(image_path, question="", min_pixels=350000, max_pixels=500000):
>     messages = [
>         {
>             "role": "user",
>             "content": [
>                 {
>                     "type": "image",
>                     "image": image_path,
>                     "max_pixels": max_pixels,
>                     "min_pixels": min_pixels,
>                 },
>                 {"type": "text", "text": question},
>             ],
>         }
>     ]
> 
>     text = processor.apply_chat_template(
>         messages, tokenize=False, add_generation_prompt=True
>     )
>     image_inputs, video_inputs = process_vision_info(messages)
> 
>     inputs = processor(
>         text=[text],
>         images=image_inputs,
>         videos=video_inputs,
>         padding=True,
>         return_tensors="pt",
>     )
>     inputs = inputs.to(device)
>     pixel_values = inputs["pixel_values"].type(torch.bfloat16)
>     with torch.no_grad():
>         image_embeds = visual_model(pixel_values, grid_thw=inputs["image_grid_thw"])
>     return inputs["image_grid_thw"], image_embeds
> 
> 
> if __name__ == "__main__":
>     image_path = "/home/work/data/xxx/up.jpeg"
>     print("Processing image...")
>     image_grid_thw1, image_embeds1 = tmp_process_image(
>         image_path, question="", min_pixels=350000, max_pixels=500000
>     )
>     print(image_embeds1)
>     print("Image processed.")
>     time.sleep(1000)
> ```
> 
> <img alt="image" width="705" src="https://private-user-images.githubusercontent.com/6668626/374438081-7f76bed9-c4b5-4bbd-87b4-b78561689d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDMxNTMsIm5iZiI6MTczMjEwMjg1MywicGF0aCI6Ii82NjY4NjI2LzM3NDQzODA4MS03Zjc2YmVkOS1jNGI1LTRiYmQtODdiNC1iNzg1NjE2ODlkNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTE0MDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjJlMzY3MGMzMjEzNzBiYTY2NmFhZjdlOWRiZWJlNDRhN2E5Y2E5ODdkNzQ2YzVlYzZmZWE5YWMyNTVlYWY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ANDgBUGa8Beu5Pibi6SwytKYJFR1jxrOJ9cqmKkeeKw">

可以问您一下，怎么只load Qwen2-vl语言模型部分的权重呀？

**Comment by whyiug** [comment]
> > I solved the problem with a smaller gpu memory. I'll post the code in case anyone else runs into a similar problem. Just look at the`load_model` section.
> > ```python
> > import torch
> > from transformers import AutoConfig
> > from transformers import AutoProcessor
> > from transformers.models.qwen2_vl.modeling_qwen2_vl import (
> >     Qwen2VisionTransformerPretrainedModel,
> > )
> > from safetensors.torch import load_file
> > from qwen_vl_utils import process_vision_info
> > import time
> > import os
> > 
> > visual_model = None
> > processor = None
> > device = "cuda"
> > 
> > 
> > def load_model():
> >     global visual_model, processor
> >     model_path = "/home/work/.cache/modelscope/hub/qwen/Qwen2-VL-7B-Instruct"
> >     config = AutoConfig.from_pretrained(model_path)
> >     visual_model = Qwen2VisionTransformerPretrainedModel._from_config(
> >         config=config.vision_config
> >     )
> >     checkpoint_path = os.path.join(model_path, "model-00001-of-00005.safetensors")
> >     checkpoint = load_file(checkpoint_path)
> >     visual_weights = {
> >         key.replace("visual.", ""): value
> >         for key, value in checkpoint.items()
> >         if key.startswith("visual.")
> >     }
> >     visual_model.load_state_dict(visual_weights, strict=False)
> >     visual_model.to(device)
> >     visual_model.eval()
> >     processor = AutoProcessor.from_pretrained(model_path)
> > 
> > 
> > load_model()
> > 
> > 
> > def tmp_process_image(image_path, question="", min_pixels=350000, max_pixels=500000):
> >     messages = [
> >         {
> >             "role": "user",
> >             "content": [
> >                 {
> >                     "type": "image",
> >                     "image": image_path,
> >                     "max_pixels": max_pixels,
> >                     "min_pixels": min_pixels,
> >                 },
> >                 {"type": "text", "text": question},
> >             ],
> >         }
> >     ]
> > 
> >     text = processor.apply_chat_template(
> >         messages, tokenize=False, add_generation_prompt=True
> >     )
> >     image_inputs, video_inputs = process_vision_info(messages)
> > 
> >     inputs = processor(
> >         text=[text],
> >         images=image_inputs,
> >         videos=video_inputs,
> >         padding=True,
> >         return_tensors="pt",
> >     )
> >     inputs = inputs.to(device)
> >     pixel_values = inputs["pixel_values"].type(torch.bfloat16)
> >     with torch.no_grad():
> >         image_embeds = visual_model(pixel_values, grid_thw=inputs["image_grid_thw"])
> >     return inputs["image_grid_thw"], image_embeds
> > 
> > 
> > if __name__ == "__main__":
> >     image_path = "/home/work/data/xxx/up.jpeg"
> >     print("Processing image...")
> >     image_grid_thw1, image_embeds1 = tmp_process_image(
> >         image_path, question="", min_pixels=350000, max_pixels=500000
> >     )
> >     print(image_embeds1)
> >     print("Image processed.")
> >     time.sleep(1000)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="705" src="https://private-user-images.githubusercontent.com/6668626/374438081-7f76bed9-c4b5-4bbd-87b4-b78561689d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDMxNTMsIm5iZiI6MTczMjEwMjg1MywicGF0aCI6Ii82NjY4NjI2LzM3NDQzODA4MS03Zjc2YmVkOS1jNGI1LTRiYmQtODdiNC1iNzg1NjE2ODlkNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTE0MDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjJlMzY3MGMzMjEzNzBiYTY2NmFhZjdlOWRiZWJlNDRhN2E5Y2E5ODdkNzQ2YzVlYzZmZWE5YWMyNTVlYWY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ANDgBUGa8Beu5Pibi6SwytKYJFR1jxrOJ9cqmKkeeKw">
> 
> 可以问您一下，怎么只load Qwen2-vl语言模型部分的权重呀？

参照 visual_weights 的写法和
https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct/blob/main/model.safetensors.index.json

**Comment by ql632** [comment]
> > > @whyiug amazing work! I'm wondering whether we can get text embedding through similar way? Do you have a try on it?
> > 
> > 
> > 没有。感觉只获取 text embedding 是没有意义的，而且这个耗时非常少。如果非要获取，可以查看这里[代码](https://github.com/huggingface/transformers/blob/8a734ea2c340beee23e665601919814918bf4c43/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1683) 我把 visual model 拆开是因为希望图片模型和文本模型分开部署，而且业务需要一图多问，这对延时和吞吐都有提升。 vllm 支持输入图片 embedding 的 PR: [vllm-project/vllm#8856](https://github.com/vllm-project/vllm/pull/8856)
> 
> 好的，感谢！我是在想能不能用图文的embedding来做图文检索任务，不知道是否有可行性。

怎么样 图文检索可行吗

**Comment by suexin27** [comment]
> > > > @whyiug amazing work! I'm wondering whether we can get text embedding through similar way? Do you have a try on it?
> > > 
> > > 
> > > 没有。感觉只获取 text embedding 是没有意义的，而且这个耗时非常少。如果非要获取，可以查看这里[代码](https://github.com/huggingface/transformers/blob/8a734ea2c340beee23e665601919814918bf4c43/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1683) 我把 visual model 拆开是因为希望图片模型和文本模型分开部署，而且业务需要一图多问，这对延时和吞吐都有提升。 vllm 支持输入图片 embedding 的 PR: [vllm-project/vllm#8856](https://github.com/vllm-project/vllm/pull/8856)
> > 
> > 
> > 好的，感谢！我是在想能不能用图文的embedding来做图文检索任务，不知道是否有可行性。
> 
> 怎么样 图文检索可行吗

您好 请问图文融合后的embedding 可以获取到吗？ 您解决了吗？

**Comment by whyiug** [comment]
> > > > > @whyiug amazing work! I'm wondering whether we can get text embedding through similar way? Do you have a try on it?
> > > > 
> > > > 
> > > > 没有。感觉只获取 text embedding 是没有意义的，而且这个耗时非常少。如果非要获取，可以查看这里[代码](https://github.com/huggingface/transformers/blob/8a734ea2c340beee23e665601919814918bf4c43/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1683) 我把 visual model 拆开是因为希望图片模型和文本模型分开部署，而且业务需要一图多问，这对延时和吞吐都有提升。 vllm 支持输入图片 embedding 的 PR: [vllm-project/vllm#8856](https://github.com/vllm-project/vllm/pull/8856)
> > > 
> > > 
> > > 好的，感谢！我是在想能不能用图文的embedding来做图文检索任务，不知道是否有可行性。
> > 
> > 
> > 怎么样 图文检索可行吗
> 
> 您好 请问图文融合后的embedding 可以获取到吗？ 您解决了吗？

你也是做检索吗？还是推理架构分离？

**Comment by linchen111** [comment]
> > > > > > [@whyiug](https://github.com/whyiug) amazing work! I'm wondering whether we can get text embedding through similar way? Do you have a try on it?
> > > > > 
> > > > > 
> > > > > 没有。感觉只获取 text embedding 是没有意义的，而且这个耗时非常少。如果非要获取，可以查看这里[代码](https://github.com/huggingface/transformers/blob/8a734ea2c340beee23e665601919814918bf4c43/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1683) 我把 visual model 拆开是因为希望图片模型和文本模型分开部署，而且业务需要一图多问，这对延时和吞吐都有提升。 vllm 支持输入图片 embedding 的 PR: [vllm-project/vllm#8856](https://github.com/vllm-project/vllm/pull/8856)
> > > > 
> > > > 
> > > > 好的，感谢！我是在想能不能用图文的embedding来做图文检索任务，不知道是否有可行性。
> > > 
> > > 
> > > 怎么样 图文检索可行吗
> > 
> > 
> > 您好 请问图文融合后的embedding 可以获取到吗？ 您解决了吗？
> 
> 你也是做检索吗？还是推理架构分离？

请问做检索的话，应该怎么拿到embedding呢？

**Comment by linchen111** [comment]
> > I solved the problem with a smaller gpu memory. I'll post the code in case anyone else runs into a similar problem. Just look at the`load_model` section.我用较小的GPU内存解决了问题。如果其他人遇到类似问题，我将发布代码。只需查看`load_model`部分即可。
> > import torch
> > from transformers import AutoConfig
> > from transformers import AutoProcessor
> > from transformers.models.qwen2_vl.modeling_qwen2_vl import (
> >     Qwen2VisionTransformerPretrainedModel,
> > )
> > from safetensors.torch import load_file
> > from qwen_vl_utils import process_vision_info
> > import time
> > import os
> > 
> > visual_model = None
> > processor = None
> > device = "cuda"
> > 
> > 
> > def load_model():
> >     global visual_model, processor
> >     model_path = "/home/work/.cache/modelscope/hub/qwen/Qwen2-VL-7B-Instruct"
> >     config = AutoConfig.from_pretrained(model_path)
> >     visual_model = Qwen2VisionTransformerPretrainedModel._from_config(
> >         config=config.vision_config
> >     )
> >     checkpoint_path = os.path.join(model_path, "model-00001-of-00005.safetensors")
> >     checkpoint = load_file(checkpoint_path)
> >     visual_weights = {
> >         key.replace("visual.", ""): value
> >         for key, value in checkpoint.items()
> >         if key.startswith("visual.")
> >     }
> >     visual_model.load_state_dict(visual_weights, strict=False)
> >     visual_model.to(device)
> >     visual_model.eval()
> >     processor = AutoProcessor.from_pretrained(model_path)
> > 
> > 
> > load_model()
> > 
> > 
> > def tmp_process_image(image_path, question="", min_pixels=350000, max_pixels=500000):
> >     messages = [
> >         {
> >             "role": "user",
> >             "content": [
> >                 {
> >                     "type": "image",
> >                     "image": image_path,
> >                     "max_pixels": max_pixels,
> >                     "min_pixels": min_pixels,
> >                 },
> >                 {"type": "text", "text": question},
> >             ],
> >         }
> >     ]
> > 
> >     text = processor.apply_chat_template(
> >         messages, tokenize=False, add_generation_prompt=True
> >     )
> >     image_inputs, video_inputs = process_vision_info(messages)
> > 
> >     inputs = processor(
> >         text=[text],
> >         images=image_inputs,
> >         videos=video_inputs,
> >         padding=True,
> >         return_tensors="pt",
> >     )
> >     inputs = inputs.to(device)
> >     pixel_values = inputs["pixel_values"].type(torch.bfloat16)
> >     with torch.no_grad():
> >         image_embeds = visual_model(pixel_values, grid_thw=inputs["image_grid_thw"])
> >     return inputs["image_grid_thw"], image_embeds
> > 
> > 
> > if __name__ == "__main__":
> >     image_path = "/home/work/data/xxx/up.jpeg"
> >     print("Processing image...")
> >     image_grid_thw1, image_embeds1 = tmp_process_image(
> >         image_path, question="", min_pixels=350000, max_pixels=500000
> >     )
> >     print(image_embeds1)
> >     print("Image processed.")
> >     time.sleep(1000)
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="54.150001525878906" height="21" src="https://private-user-images.githubusercontent.com/6668626/374438081-7f76bed9-c4b5-4bbd-87b4-b78561689d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDMxNTMsIm5iZiI6MTczMjEwMjg1MywicGF0aCI6Ii82NjY4NjI2LzM3NDQzODA4MS03Zjc2YmVkOS1jNGI1LTRiYmQtODdiNC1iNzg1NjE2ODlkNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTE0MDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjJlMzY3MGMzMjEzNzBiYTY2NmFhZjdlOWRiZWJlNDRhN2E5Y2E5ODdkNzQ2YzVlYzZmZWE5YWMyNTVlYWY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ANDgBUGa8Beu5Pibi6SwytKYJFR1jxrOJ9cqmKkeeKw">
> 
> 可以问您一下，怎么只load Qwen2-vl语言模型部分的权重呀？

When I get image/video embeddings like this. Can I  use this for like text-query-image or image-duplicate ？

**Comment by whyiug** [comment]
> > > [@whyiug](https://github.com/whyiug) amazing work! I'm wondering whether we can get text embedding through similar way? Do you have a try on it?
> > 
> > 
> > 没有。感觉只获取 text embedding 是没有意义的，而且这个耗时非常少。如果非要获取，可以查看这里[代码](https://github.com/huggingface/transformers/blob/8a734ea2c340beee23e665601919814918bf4c43/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1683) 我把 visual model 拆开是因为希望图片模型和文本模型分开部署，而且业务需要一图多问，这对延时和吞吐都有提升。 vllm 支持输入图片 embedding 的 PR: [vllm-project/vllm#8856](https://github.com/vllm-project/vllm/pull/8856)
> 
> 你好，这个代码的视觉部分我测试了下，是能够获取向量的，但和vllm自身计算的视觉向量间有一定误差，观察了下向量元素小数点两位就有一定差异了，请问有什么办法解决吗

一般跟浮点数精度、attenton 后端（flash attention)有关。
当然即使相同算法，不同显卡的也有微小差异。

**Comment by jianbaba** [comment]
> As the title says. we need to embed the image with visual part separately.
> 
> For now , i use the code bellow. Trouble is, I still loaded all the parameters. Can you guys give me some tips to simplify the code?
> 
> from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor, Qwen2VLConfig
> from qwen_vl_utils import process_vision_info
> import time
> import torch
> 
> model_name = "Qwen/Qwen2-VL-7B-Instruct"
> # model = Qwen2VLForConditionalGeneration.from_pretrained(model_name, torch_dtype="auto", device_map="auto")
> model = Qwen2VLForConditionalGeneration.from_pretrained(model_name)
> visual_model = model.visual
> visual_model.to("cuda")
> 
> min_pixels = 100000
> max_pixels = 500000
> processor = AutoProcessor.from_pretrained(model_name, min_pixels=min_pixels, max_pixels=max_pixels)
> 
> IMAGE_PATH = '/home/xxxx.jpeg'
> question = "描述这张图片。"
> messages = [
>     {
>         "role": "user",
>         "content": [
>             {
>                 "type": "image",
>                 "image": IMAGE_PATH,
>                 'max_pixels': max_pixels,
>                 'min_pixels': min_pixels,
>             },
>             {"type": "text", "text": question},
>         ],
>     }
> ]
> 
> text = processor.apply_chat_template(
>     messages, tokenize=False, add_generation_prompt=True
> )
> image_inputs, video_inputs = process_vision_info(messages)
> 
> inputs = processor(
>     text=[text],
>     images=image_inputs,
>     videos=video_inputs,
>     padding=True,
>     return_tensors="pt",
> )
> # inputs = inputs.to("cuda")
> inputs = inputs.to("cuda")
> 
> 
> pixel_values = inputs["pixel_values"].type(torch.bfloat16)
> 
> image_embeds = visual_model(pixel_values, grid_thw=inputs["image_grid_thw"])
> print(image_embeds.shape)

大佬你好，请问下，如何将不同的组件分开加载，然后再将各个组件结果串在一起呢？有代码可以分享下吗？

**Comment by whyiug** [comment]
> > As the title says. we need to embed the image with visual part separately.
> > For now , i use the code bellow. Trouble is, I still loaded all the parameters. Can you guys give me some tips to simplify the code?
> > from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor, Qwen2VLConfig
> > from qwen_vl_utils import process_vision_info
> > import time
> > import torch
> > model_name = "Qwen/Qwen2-VL-7B-Instruct"
> > # model = Qwen2VLForConditionalGeneration.from_pretrained(model_name, torch_dtype="auto", device_map="auto")
> > model = Qwen2VLForConditionalGeneration.from_pretrained(model_name)
> > visual_model = model.visual
> > visual_model.to("cuda")
> > min_pixels = 100000
> > max_pixels = 500000
> > processor = AutoProcessor.from_pretrained(model_name, min_pixels=min_pixels, max_pixels=max_pixels)
> > IMAGE_PATH = '/home/xxxx.jpeg'
> > question = "描述这张图片。"
> > messages = [
> > {
> > "role": "user",
> > "content": [
> > {
> > "type": "image",
> > "image": IMAGE_PATH,
> > 'max_pixels': max_pixels,
> > 'min_pixels': min_pixels,
> > },
> > {"type": "text", "text": question},
> > ],
> > }
> > ]
> > text = processor.apply_chat_template(
> > messages, tokenize=False, add_generation_prompt=True
> > )
> > image_inputs, video_inputs = process_vision_info(messages)
> > inputs = processor(
> > text=[text],
> > images=image_inputs,
> > videos=video_inputs,
> > padding=True,
> > return_tensors="pt",
> > )
> > # inputs = inputs.to("cuda")
> > inputs = inputs.to("cuda")
> > pixel_values = inputs["pixel_values"].type(torch.bfloat16)
> > image_embeds = visual_model(pixel_values, grid_thw=inputs["image_grid_thw"])
> > print(image_embeds.shape)
> 
> 大佬你好，请问下，如何将不同的组件分开加载，然后再将各个组件结果串在一起呢？有代码可以分享下吗？

去年写的，工程上做到架构分离，还有些复杂

**Comment by rickakkerman** [comment]
> > I solved the problem with a smaller gpu memory. I'll post the code in case anyone else runs into a similar problem. Just look at the`load_model` section.
> > import torch
> > from transformers import AutoConfig
> > from transformers import AutoProcessor
> > from transformers.models.qwen2_vl.modeling_qwen2_vl import (
> >     Qwen2VisionTransformerPretrainedModel,
> > )
> > from safetensors.torch import load_file
> > from qwen_vl_utils import process_vision_info
> > import time
> > import os
> > 
> > visual_model = None
> > processor = None
> > device = "cuda"
> > 
> > 
> > def load_model():
> >     global visual_model, processor
> >     model_path = "/home/work/.cache/modelscope/hub/qwen/Qwen2-VL-7B-Instruct"
> >     config = AutoConfig.from_pretrained(model_path)
> >     visual_model = Qwen2VisionTransformerPretrainedModel._from_config(
> >         config=config.vision_config
> >     )
> >     checkpoint_path = os.path.join(model_path, "model-00001-of-00005.safetensors")
> >     checkpoint = load_file(checkpoint_path)
> >     visual_weights = {
> >         key.replace("visual.", ""): value
> >         for key, value in checkpoint.items()
> >         if key.startswith("visual.")
> >     }
> >     visual_model.load_state_dict(visual_weights, strict=False)
> >     visual_model.to(device)
> >     visual_model.eval()
> >     processor = AutoProcessor.from_pretrained(model_path)
> > 
> > 
> > load_model()
> > 
> > 
> > def tmp_process_image(image_path, question="", min_pixels=350000, max_pixels=500000):
> >     messages = [
> >         {
> >             "role": "user",
> >             "content": [
> >                 {
> >                     "type": "image",
> >                     "image": image_path,
> >                     "max_pixels": max_pixels,
> >                     "min_pixels": min_pixels,
> >                 },
> >                 {"type": "text", "text": question},
> >             ],
> >         }
> >     ]
> > 
> >     text = processor.apply_chat_template(
> >         messages, tokenize=False, add_generation_prompt=True
> >     )
> >     image_inputs, video_inputs = process_vision_info(messages)
> > 
> >     inputs = processor(
> >         text=[text],
> >         images=image_inputs,
> >         videos=video_inputs,
> >         padding=True,
> >         return_tensors="pt",
> >     )
> >     inputs = inputs.to(device)
> >     pixel_values = inputs["pixel_values"].type(torch.bfloat16)
> >     with torch.no_grad():
> >         image_embeds = visual_model(pixel_values, grid_thw=inputs["image_grid_thw"])
> >     return inputs["image_grid_thw"], image_embeds
> > 
> > 
> > if __name__ == "__main__":
> >     image_path = "/home/work/data/xxx/up.jpeg"
> >     print("Processing image...")
> >     image_grid_thw1, image_embeds1 = tmp_process_image(
> >         image_path, question="", min_pixels=350000, max_pixels=500000
> >     )
> >     print(image_embeds1)
> >     print("Image processed.")
> >     time.sleep(1000)
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="705" src="https://private-user-images.githubusercontent.com/6668626/374438081-7f76bed9-c4b5-4bbd-87b4-b78561689d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDMxNTMsIm5iZiI6MTczMjEwMjg1MywicGF0aCI6Ii82NjY4NjI2LzM3NDQzODA4MS03Zjc2YmVkOS1jNGI1LTRiYmQtODdiNC1iNzg1NjE2ODlkNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTE0MDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjJlMzY3MGMzMjEzNzBiYTY2NmFhZjdlOWRiZWJlNDRhN2E5Y2E5ODdkNzQ2YzVlYzZmZWE5YWMyNTVlYWY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ANDgBUGa8Beu5Pibi6SwytKYJFR1jxrOJ9cqmKkeeKw">
> 
> 可以问您一下，怎么只load Qwen2-vl语言模型部分的权重呀？

You don't have to process the image in the chat_template format. You can call processor.image_processor(images=[img], return_tensors="pt), which gives you the pixel_values and the image_grid_thw
