### ISSUE TITLE
OOM Error

### ISSUE THREAD

**Issue by Mrzhang1999** [QwenLM/Qwen2-VL#32]
使用huggingface的单图推理case，推理100张左右的图像后，显卡显存从37G直接飙升到68G，显存利用率下降，并且后续的图片推理显存也在增加，直到报OOM，推理停止：
![image](https://github.com/user-attachments/assets/c3d56f65-f0b8-4db7-9594-71433c9d6d1f)
![image](https://github.com/user-attachments/assets/681dce56-7585-49fd-929b-3353d16bdc30)

**Comment by simonJJJ** [comment]
Hi @Mrzhang1999, would you mind providing the inference code?

**Comment by Mrzhang1999** [comment]
I've realized it's my own problem. When I don't limit the image pixels, the card is very prone to OOM when using batch inference.

**Comment by stomachacheGE** [comment]
> I've realized it's my own problem. When I don't limit the image pixels, the card is very prone to OOM when using batch inference.

hi, I met the same problem. How did you solve this problem?

**Comment by Mrzhang1999** [comment]
# The default range for the number of visual tokens per image in the model is 4-16384. You can set min_pixels and max_pixels according to your needs, such as a token count range of 256-1280, to balance speed and memory usage.
# min_pixels = 256*28*28
# max_pixels = 1280*28*28
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

**Comment by hm123450** [comment]
> # The default range for the number of visual tokens per image in the model is 4-16384. You can set min_pixels and max_pixels according to your needs, such as a token count range of 256-1280, to balance speed and memory usage.
> # min_pixels = 256_28_28
> # max_pixels = 1280_28_28
> # processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

大佬我有个问题，比如说您做的单图推理case，不管我们max_pixel设置为多少，它难道不应该是推理完一张图片之后，恢复显存，继续推理下一张，所以它的显存不应该没有变化才对么？

**Comment by linuxsirhjl** [comment]
Have you solved it
