### ISSUE TITLE
Qwen2-VL-72b on 阿里云百炼无法设置temperature

### ISSUE THREAD

**Issue by zfj1998** [QwenLM/Qwen2-VL#33]
按照https://help.aliyun.com/zh/model-studio/developer-reference/qwen-vl-api
文档中的dashscope sdk设置了temperature进行采样，可是哪怕温度0.8，多次生成的内容也没有区别

**Comment by Firmament-cyou** [comment]
> 按照https://help.aliyun.com/zh/model-studio/developer-reference/qwen-vl-api 文档中的dashscope sdk设置了temperature进行采样，可是哪怕温度0.8，多次生成的内容也没有区别

您好，百炼 api 可以配合 seed 参数获取不同的生成结果，参数中传入随机的 seed 即可。

**Comment by zfj1998** [comment]
Thanks! 还想请问百炼API可以设置采样次数吗，类似OpenAI API中的n，一次生成n个采样样本

**Comment by Firmament-cyou** [comment]
> Thanks! 还想请问百炼API可以设置采样次数吗，类似OpenAI API中的n，一次生成n个采样样本

暂时在 Qwen2-VL 模型的 api 上没有支持 n 参数。
