### ISSUE TITLE
72b 模型对显卡的硬件要求说明

### ISSUE THREAD

**Issue by V-yw** [QwenLM/Qwen2-VL#340]
<img width="818" alt="image" src="https://github.com/user-attachments/assets/eba8985c-fe1b-48b3-b705-874639fa7acd">

想问一下,这里的GPU memroy 是单卡的大小,还是可以多张一起加起来的大小.

**Comment by kq-chen** [comment]
多张卡加起来的总memory

**Comment by V-yw** [comment]
感谢!
