### ISSUE TITLE
𝟷𝟾+ 𝗏𝚒𝗋𝖺𝗅 𝖲𝗈𝗉𝗁𝗂𝖾 𝖱𝖺𝗂𝗇 𝖲𝗉𝗂𝖽𝚎𝗋𝗆𝖺𝗇 𝗆𝗆𝚜 𝖫𝖾𝚊𝚔𝖾𝖽 𝗏𝚒𝖽𝖾𝗈

### ISSUE THREAD

**Issue by sports34** [QwenLM/Qwen2-VL#356]
𝟷𝟾+ 𝗏𝚒𝗋𝖺𝗅 𝖲𝗈𝗉𝗁𝗂𝖾 𝖱𝖺𝗂𝗇 𝖲𝗉𝗂𝖽𝚎𝗋𝗆𝖺𝗇 𝗆𝗆𝚜 𝖫𝖾𝚊𝚔𝖾𝖽 𝗏𝚒𝖽𝖾𝗈

[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://cutli.me/eXMwl)

[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://cutli.me/eXMwl)
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

**Comment by Vilhumvi** [comment]
[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)




[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)


[🌐 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
[🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖥𝖱𝖤𝖤 𝖭𝖮𝖶](https://bit.ly/3ALZbWv)
