### ISSUE TITLE
视频的抽帧策略是什么？

### ISSUE THREAD

**Issue by WangQvQ** [QwenLM/Qwen2-VL#36]
目前Qwen2-VL实现了端到端的视频内容理解，我想请问，在模型的黑盒部分，是采用的什么样的抽帧策略呢，能否分享下这部分的技术细节。感谢~

**Comment by ShuaiBai623** [comment]
https://github.com/kq-chen/qwen-vl-utils/blob/b5994a45942cc18995d8d2203f11ae1147c9f059/src/qwen_vl_utils/vision_process.py#L118 可以参考工具的fetch_video 函数

**Comment by jinze1994** [comment]
如上所述，我们的抽帧代码目前在 https://github.com/kq-chen/qwen-vl-utils 。由于我们模型采用了是动态分辨率，因此可以自由调整视频输入的FPS和视频分辨率。上述代码中，默认的视频抽帧策略和分辨率设置来自于对 [Video-MME](https://video-mme.github.io/home_page.html#leaderboard) 评测的最佳实践。概括的说是：

1. 每个视频默认 fps 为 2.0，若 nframes 超过 768 帧，则最大单个视频 768 帧
2. 单个视频最长输入LLM的序列长度为30720，单帧最大600K像素，即 `max_pixels = (factor ** 2) * min(768, (max_tokens / num_frames * 2))`。其中`factor=28`，`max_tokens=30720`，`num_frames=duration*fps`

需要注意，以上策略是通用配置。您可以根据需要自由调整参数策略：
- 如果需要理解时长更长的视频，可以减小fps；
- 如果需要理解快速变化内容的视频，可以增大fps；
- 如果需要理解高清视频的细节，可以增大max_pixels

调整参数的教程参考：https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#using---transformers-to-chat 下的Video Inference小节

**Comment by WangQvQ** [comment]
@ShuaiBai623 @jinze1994 了解了，非常感谢您二人的回答~

**Comment by JuanJia** [comment]
@ShuaiBai623 @jinze1994 非常感谢你们的杰出工作，请问一下，在预训练时，视频的抽帧策略也是和上面推理时的策略一样么？

**Comment by pidgey016** [comment]
@ShuaiBai623 factor=28的话，这个地方是不是有点问题？

![Image](https://github.com/user-attachments/assets/1d1b59ff-8395-4166-98ba-863c9872410b)

**Comment by jiinhui** [comment]
> [@ShuaiBai623](https://github.com/ShuaiBai623) [@jinze1994](https://github.com/jinze1994) 非常感谢你们的杰出工作，请问一下，在预训练时，视频的抽帧策略也是和上面推理时的策略一样么？

@ShuaiBai623 @JuanJia   同问这个问题， 想问问  训练时，视频的抽帧策略是怎样的？

**Comment by 24088465** [comment]
您好，qwen3vl的动态抽帧策略也和这个一致吗
