### ISSUE TITLE
AttributeError: 'VisionAttention' object has no attribute 'head_dim'

### ISSUE THREAD

**Issue by Betty-J** [QwenLM/Qwen2-VL#38]
Hello, 
I am encountering the following error while fine-tuning the **qwen2-vl-2b-instruc**t with the Swift framework: 
_File "./miniconda3/envs/swift/lib/python3.11/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 296, in forward
[rank1]: attn_weights = torch.matmul(q, k.transpose(1, 2)) / math.sqrt(self.head_dim)
AttributeError: 'VisionAttention' object has no attribute 'head_dim'._ 

After checking the original **modeling_qwen2_vl.py** file, I found that 'self.head_dim' is indeed not defined in VisionAttention. How can I resolve it?
![截屏2024-08-30 17 51 48](https://github.com/user-attachments/assets/254ffb3f-b8ca-4884-b7df-0f667f9dad31)

**Comment by dongZheX** [comment]
when i set attn_implementation="eager", this error happened.

**Comment by simonJJJ** [comment]
@Betty-J thanks for pointing this out, we will fix it.

**Comment by simonJJJ** [comment]
we opened a [PR](https://github.com/huggingface/transformers/pull/33213) for fixing this.

**Comment by ApolloRay** [comment]
Has it already fixed ? I meet the same question.

**Comment by nihirv** [comment]
Simple fix -- just add this line in the VisionAttention class: `self.head_dim = dim // num_heads` (site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py)

**Comment by deepbodo** [comment]
> Simple fix -- just add this line in the VisionAttention class: `self.head_dim = dim // num_heads` (site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py)

where to add it in the forward pass or the initi

**Comment by lonnex** [comment]
torch版本更新到2.2.2即可
