### ISSUE TITLE
image_token_id question and GPU memory cost

### ISSUE THREAD

**Issue by nemonameless** [QwenLM/Qwen2-VL#40]
```
[rank1]:   File "/root/miniconda3/envs/llamafac/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1584, in forward
[rank1]:     inputs_embeds[image_mask] = image_embeds
[rank1]: RuntimeError: shape mismatch: value tensor of shape [4880, 1536] cannot be broadcast to indexing result of shape [1006, 1536]
```
看起来是 image_mask = input_ids == self.config.image_token_id 这句的问题，造的数据json里写<image> 或者 <|image_pad|> 均有这个问题。开源权重里additional_special_tokens是 "<|image_pad|>"， https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct/blob/main/tokenizer_config.json#L117 ，希望可以放一个能完整训练的1000条级别数据的demo json例子，并联动LLaMA-Factory 修复下。谢谢。

另外2b 7b的full sft和lora显存大致都需要多少可以列下吗? 谢谢。

**Comment by simonJJJ** [comment]
可以参考LLaMA-Factory最新的commit，造的数据[例子](https://github.com/hiyouga/LLaMA-Factory/blob/main/data/mllm_demo.json#L5)应该把`<|image_pad|>`换成了`<image>`

**Comment by huynhbaobk** [comment]
Any solution for this. Thanks

**Comment by nemonameless** [comment]
发现如果是2000*2000的高分辨率图片，制作的json数据训练时依然会产生上面的问题；如果只是600*600级别的图片的数据则不会。数据预处理的逻辑是否还有点问题，若改了数据预处理方式精度会掉很多吗？

**Comment by nemonameless** [comment]
发现是第一次训数据集时会制作很慢，后续都会读cache是很快加载上了。但是还有个问题是造的cache太过庞大，几百k的sft数据做出了1T的cache，如果切换2B模型训又会再造1T的cache，实在太占空间了，不用cache前期加载数据又等待非常慢。希望可以联合 LLaMA-Factory 优化下，只能训极少量sft数据感觉还是不够的。谢谢。

**Comment by hiyouga** [comment]
@nemonameless cache 的问题在最新版 llamafactory 已经得到修复，欢迎测试
