### ISSUE TITLE
pip install git+https://github.com/huggingface/transformers accelerate

### ISSUE THREAD

**Issue by eternal8080** [QwenLM/Qwen2-VL#41]
被墙了，这个有替换的方法吗

**Comment by RemSynch** [comment]
`pip install git+https://github.com/huggingface/transformers -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com`

**Comment by kkiskkk** [comment]
直接访问https://github.com/huggingface/transformers/**commit**/21fac7abba2a37fae86106f87fcf9974fd1e3830
中间加个commit，这个就会带你到该提交的详细页面。
然后再提交页面上找到“Browse files”按钮，点击后会显示这个提交的文件列表。
点code按钮然后download ZIP 下载ZIP文件。
解压之后进入页面 使用**pip install .** 命令安装依赖即可解决

**Comment by hunter2009pf** [comment]
> 直接访问https://github.com/huggingface/transformers/**commit**/21fac7abba2a37fae86106f87fcf9974fd1e3830 中间加个commit（手动输入 不要直接从我发的这个上面打开），这个就会带你到该提交的详细页面。 然后再提交页面上找到“Browse files”按钮，点击后会显示这个提交的文件列表。 点code按钮然后download ZIP 下载ZIP文件。 解压之后进入页面 使用**pip install .** 命令安装依赖即可解决

oh my friend, you are true genius!
