### ISSUE TITLE
7b-awq模型在A10上使用VLLM镜像部署，显存总是oom。

### ISSUE THREAD

**Issue by ZhanNicky** [QwenLM/Qwen2-VL#482]
请问我部署qwen2VL-7b-awq模型，使用VLLM镜像，总是会报超过显存的问题。
我使用的是A10的24Gb的卡。
![image](https://github.com/user-attachments/assets/c9a2ffca-2342-4090-90dc-a23cc9bb5350)

**Comment by ML-GCN** [comment]
你可以将这个参数--gpu-memory-utilization 设置小一些 比如0.7

**Comment by ZhanNicky** [comment]
> 你可以将这个参数--gpu-memory-utilization 设置小一些 比如0.7

感谢提醒，这个参数改了之后就好了。

**Comment by ZhanNicky** [comment]
> 你可以将这个参数--gpu-memory-utilization 设置小一些 比如0.7

感谢提醒，这个参数改了之后就好了。

**Comment by flychen59** [comment]
可以问一下，如何用qwen2vl-7b做的awq量化吗,可以共享一下pip list吗，谢谢
