### ISSUE TITLE
Was M-ROPE used in the training of Qwen2-VL?

### ISSUE THREAD

**Issue by Wiselnn570** [QwenLM/Qwen2-VL#488]
Recently, I used the llama-factory repository to fine-tune Qwen2-VL and found that it uses 1D-ROPE (for text, images, and videos) across all modalities during training. Is this normal, or could it be a potential bug in the llama-factory repository?

**Comment by ShuaiBai623** [comment]
"uses 1D RoPE during training" is not normal. We have already submitted a PR to Transformer addressing this issue. You can refer to this modification to fine-tune the model correctly.
[](https://github.com/huggingface/transformers/pull/33487)

**Comment by zhang9302002** [comment]
Same concern, could you share the PR link?

**Comment by Wiselnn570** [comment]
> Same concern, could you share the PR link?

https://github.com/huggingface/transformers/pull/33487/commits
