### ISSUE TITLE
vllm 推理结果每次都随机变化，transformers and qwen_vl_utils 结果固定

### ISSUE THREAD

**Issue by lxiaoxiaoxing** [QwenLM/Qwen2-VL#496]
每次相同的输入，vllm 推理结果每次都随机变化，transformers and qwen_vl_utils 结果固定，我想要用vllm每次输出固定结果，怎么做

**Comment by hunter2009pf** [comment]
调用vllm接口时，temperature是一个可选入参，这个输入值你固定了吗？
