### ISSUE TITLE
 Could you please provide reference materials for reproducing the benchmark results, such as Chain of Thought prompts, result extraction scripts, etc., so that we can replicate the evaluation benchmark results?

### ISSUE THREAD

**Issue by Past-Tang** [QwenLM/Qwen2-VL#50]
Could you please provide reference materials for reproducing the benchmark results, such as Chain of Thought prompts, result extraction scripts, etc., so that we can replicate the evaluation benchmark results?

**Comment by lsnls** [comment]
Hello, @Past-Tang , Could you solve the problem? I have the same confusion.
