### ISSUE TITLE
能支持其他Pytorch版本吗？

### ISSUE THREAD

**Issue by PolarisHsu** [QwenLM/Qwen2-VL#52]
目前仅支持2.4，2.4以下版本会报错，但我们的集群环境目前还不支持这么新的版本。

**Comment by kq-chen** [comment]
try `pip install git+https://github.com/huggingface/transformers.git@27903de`

The constraint `torch>2.4` is not introduced by qwen2-vl, but stems from a recent [bug](https://github.com/huggingface/transformers/pull/33177) in `transformers`. Although the [fix](https://github.com/huggingface/transformers/pull/33177) has been proposed, it has not yet been merged.

As a temporary workaround, you can install transformers from a commit before [PR #31502](https://github.com/huggingface/transformers/commits/main/#27903de:~:text=Granite%20language%20models%20(%2331502)).

**Comment by GeLee-Q** [comment]
是不是nn.RMS 不支持的问题
可以在` /transformers/pytorch_utils.py` 中把
`# ALL_LAYERNORM_LAYERS = [nn.LayerNorm, nn.RMSNorm]`
这一行注释掉

**Comment by kq-chen** [comment]
the [fix](https://github.com/huggingface/transformers/pull/33177) has been merged. now, you can try qwen2-vl with `torch<2.4`.
