### ISSUE TITLE
Chain of Thought prompts

### ISSUE THREAD

**Issue by Past-Tang** [QwenLM/Qwen2-VL#54]
Would it be possible for you to kindly share any reference materials that could assist us in reproducing the benchmark results? Specifically, we would greatly appreciate access to resources like Chain of Thought prompts, result extraction scripts, and any other relevant documentation. Your assistance would be invaluable in helping us replicate the evaluation benchmark results.

**Comment by logicwong** [comment]
1. We'll submit a PR to [VLMEvalKit](https://github.com/open-compass/VLMEvalKit) soon; we recommend using it to reproduce the Qwen2-VL results.
2. For Chain of Thought prompts, simply append "Let's think step by step" to your question and give it a try.

**Comment by Past-Tang** [comment]
> 1. We'll submit a PR to [VLMEvalKit](https://github.com/open-compass/VLMEvalKit) soon; we recommend using it to reproduce the Qwen2-VL results.我们将很快提交一个 PR 到 VLMEvalKit；我们建议使用它来重现 Qwen2-VL 的结果。
> 2. For Chain of Thought prompts, simply append "Let's think step by step" to your question and give it a try.对于链式思考的提示，只需将“让我们一步一步思考”附加到您的问题后，然后尝试一下。

Thank you for your reply. We would like to receive more information about prompts. Thank you very much

**Comment by kq-chen** [comment]
the prompts has update. you can check [qwen2_vl/prompt.py](https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/vlm/qwen2_vl/prompt.py) and [qwen2_vl/model.py](https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/vlm/qwen2_vl/model.py)
