### ISSUE TITLE
vllm启动qwen2_vl-7b的模型出现safetensors_rust.SafetensorError错误

### ISSUE THREAD

**Issue by night666e** [QwenLM/Qwen2-VL#559]
命令：python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-VL-7B-Instruct --model Qwen2-VL-7B-Instruct
报错：safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
ERROR 11-27 13:59:36 api_server.py:188] RPCServer process died before responding to readiness probe

**Comment by liuyang811** [comment]
请问你解决了吗

**Comment by night666e** [comment]
> 请问你解决了吗

解决了，就是模型文件没下完整
