### ISSUE TITLE
Interleaved images and text

### ISSUE THREAD

**Issue by pbarker** [QwenLM/Qwen2-VL#587]
The training scripts make it very clear how to train on interleaved images and text by adding the `<image>` token. However its not clear how to do this at inference time.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the `web_demo_streaming/app.py` file to allow users to input interleaved images and text, and process them correctly during inference. This includes updating the UI to support image uploads within text input, and modifying the message processing to handle the '<image>' token.

You can review changes in this commit: https://github.com/mnmnk43434/QwenLM-Qwen2-VL-587/commit/31c97b04628d36ab11c62bd803e2d6854e94a813.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by GasolSun36** [comment]
> The training scripts make it very clear how to train on interleaved images and text by adding the `<image>` token. However its not clear how to do this at inference time.

Hi, did you solve this question?
