### ISSUE TITLE
如何给字典新增加一些special token, 之前qwen-vl 字典里面还有<|extra_*|> 可以用。请问qwen2-vl 如何增加或者使用特殊符号呢？

### ISSUE THREAD

**Issue by qxhhou** [QwenLM/Qwen2-VL#603]
如何在qwen2-vl加入新的特殊字符？
测试 qwen2-vl 的 len(tokenizer)是151657 ，但是vocab_size 是152064  ，是不是还有一些字符可以使用？？

**Comment by yyyyll0ss** [comment]
![Image](https://github.com/user-attachments/assets/b93b5be4-354e-4073-8aaf-0d943859762c)
你好，请问在tokenizer_config中添加新特殊字符的时候，比如在图中这个字符之后添加，编号可以直接顺延嘛？（只要不超过152064），content可以自己定义吗？
