### ISSUE TITLE
How to specify the output as json format?  如何指定用json格式输出

### ISSUE THREAD

**Issue by yyxssm** [QwenLM/Qwen2-VL#610]
I have found that when using [api](https://bailian.console.aliyun.com/#/model-market/detail/qwen2-vl-7b-instruct), we can use `response_format={"type": "json_object"}` to specify the output format. I have tried this successfully.

But when I want to inference locally, I don't know where can I use the `response_format` key.

I have tried in 
```python
processor = AutoProcessor.from_pretrained(MODEL_PATH, response_format={"type": "json_object"})
```
and I have gave the "use json form in output" as instruct, but it doesn't work. How to specify the json as the output format?

**Question in Chinese:**
如何在本地推理时指定用json格式输出？在调用api时可以使用`response_format={"type": "json_object"}`。请问在本地推理时，应该在哪里调用`response_format={"type": "json_object"}`这个变量？

**Comment by yyxssm** [comment]
The issue has been resolved. The 2B model has poor instruction-following ability. I switch to 7B model and it can follow my instruction.

**Comment by CeyaoZhang** [comment]
Can u show me how to solve it by inference locally? Thx

**Comment by SunnyLi2015** [comment]
I met the same issue, always output "addCriterion" at the end

**Comment by yyxssm** [comment]
You need to change the prompt to json format, for example, you can use json format prompt like this


```json
{"text":  "You are a helpful assistant",
"output_format": "请以JSON格式输出图中所有物品bbox的坐标。<|vision_start|><|image_pad|><|vision_end|><|im_end|><|im_start|>"
}
```

**Comment by yyxssm** [comment]
Yes, sometimes it fails. But I have not find a better way.



---- 回复的原邮件 ----
| 发件人 | shanshan ***@***.***> |
| 日期 | 2025年03月24日 22:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [QwenLM/Qwen2.5-VL] How to specify the output as json format?  如何指定用json格式输出 (Issue #610) |

Does it consistently generate valid JSON with this prompt? I'm using the 7B-instruct model, but it occasionally fails to follow instructions and outputs invalid JSON.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

cooleel left a comment (QwenLM/Qwen2.5-VL#610)

Does it consistently generate valid JSON with this prompt? I'm using the 7B-instruct model, but it occasionally fails to follow instructions and outputs invalid JSON.
