### ISSUE TITLE
qwen2-vl-72B在V100上使用gptq量化报CUDA out of memory

### ISSUE THREAD

**Issue by diandianliu** [QwenLM/Qwen2-VL#619]
qwen2-vl-72B使用https://github.com/kq-chen/AutoGPTQ 中的方法在V100上量化CUDA out of memory错误
（相同步骤能成功量化qwen2-vl-2B模型）
请问针对比较大的模型是有什么参数需要设置吗
![微信图片_20241226124610](https://github.com/user-attachments/assets/a8897d2c-a772-4b8c-b282-87beb2377ed9)

环境：
python 3.10
torch  2.5.1
torchvison  0.20.0
auto-gptq 0.6.0.dev0+cu1210
qwen-vl-utils 0.0.8
显卡
nvidia V100   32G
cuda version 12.2

**Comment by DAAworld** [comment]
显存有点小吧72B跟2B用的显存能一样吗

**Comment by diandianliu** [comment]
> 显存有点小吧72B跟2B用的显存能一样吗

autoqput量化72B模型最小显存需要多少，我现在有4张V100，但只用了一张，有没有办法开启4卡量化

**Comment by diandianliu** [comment]
If I not set  model.to("cuda"), quant error:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_bmm)

**Comment by diandianliu** [comment]
soved it  as https://github.com/huggingface/transformers/pull/33742 describe
transformers 4.47.1
