### ISSUE TITLE
qwen_vl_utils中video处理的问题

### ISSUE THREAD

**Issue by Lanbai-eleven** [QwenLM/Qwen2-VL#70]
视频处理的流程是先 处理出视频的帧数 再 处理每一帧的图像
处理视频帧数的时候以默认的 FRAME_FACTOR 辅助求出所需要取的总帧数 nframes
但是为何在 处理已提取的帧图像的时候 所使用的factor还是用帧数的 FRAME_FACTOR 而不是针对图像尺寸的 IMAGE_FACTOR

**Comment by kq-chen** [comment]
good catch, thanks! we will fix it asap.

**Comment by kq-chen** [comment]
the bug has been fixed. you can reinstall the qwen-vl-utils by `pip install qwen-vl-utils -i https://pypi.python.org/simple -U` to use the latest version.
