### ISSUE TITLE
关于多图微调的问题

### ISSUE THREAD

**Issue by Akhim-yun** [QwenLM/Qwen2-VL#72]
我注意到qwen2-VL给出的官方数据集示例是
[
  {
    "messages": [
      {
        "content": "<image>Who are they?",
        "role": "user"
      },
      {
        "content": "They're Kane and Gretzka from Bayern Munich.",
        "role": "assistant"
      },
      {
        "content": "What are they doing?<image>",
        "role": "user"
      },
      {
        "content": "They are celebrating on the soccer field.",
        "role": "assistant"
      }
    ],
    "images": [
      "mllm_demo_data/1.jpg",
      "mllm_demo_data/1.jpg"
    ]
  },
]
请问如果我输入6张图片，如何在content中表示我要根据第几张图片提问呢？

**Comment by ShuaiBai623** [comment]
<image> 用于标识图片位置，参考https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#data-preparation

**Comment by YoloBird** [comment]
@ShuaiBai623 在微调时，目前是不是没有微调框架支持这样的ID指定

**Comment by linengcs** [comment]
> [@ShuaiBai623](https://github.com/ShuaiBai623) 在微调时，目前是不是没有微调框架支持这样的ID指定

请问你解决了这个问题嘛
