### ISSUE TITLE
File Missed

### ISSUE THREAD

**Issue by syspider** [QwenLM/Qwen2-VL#73]
![image](https://github.com/user-attachments/assets/d27db9a7-5b97-458f-8905-2d268de997d3)

At current time 1514-0902-2024, the LLaMA-Factory repo doesn't contain qwen2vl_lora_dpo.yaml which is mentioned in Qwen2-VL's training section.

Any ideas to find it ?

**Comment by ShuaiBai623** [comment]
https://github.com/hiyouga/LLaMA-Factory/blob/main/examples/train_lora/qwen2vl_lora_dpo.yaml

**Comment by syspider** [comment]
> https://github.com/hiyouga/LLaMA-Factory/blob/main/examples/train_lora/qwen2vl_lora_dpo.yaml

Thank you for the info! I will close this issue as completed.
