### ISSUE TITLE
请问有发布72b权重的计划吗？大概什么时候会发布呢？

### ISSUE THREAD

**Issue by hb-jw** [QwenLM/Qwen2-VL#75]
请问有发布72b权重的计划吗？大概什么时候会发布呢？

**Comment by logicwong** [comment]
再等等哈，我们内部也还在修一些问题，希望拿个更好的版本出来

**Comment by Galleons2029** [comment]
> 再等等哈，我们内部也还在修一些问题，希望拿个更好的版本出来

加油！感谢能提供这么棒的模型！
