### ISSUE TITLE
生成message报错： can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by Potato-wll** [QwenLM/Qwen2-VL#79]
这是我的推理代码，使用的是官方推荐的，执行到processor.apply_chat_template(messages,tokenize=False,add_generation_prompt=True)就会报错：
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "/home/wangll/llm/model_download_demo/models/qwen/Qwen2-7B-Instruct", torch_dtype="auto", device_map="auto"
)
processor = AutoProcessor.from_pretrained("/home/wangll/llm/model_download_demo/models/qwen/Qwen2-7B-Instruct")
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)

报错信息如下：
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[15], line 2
      1 # Preparation for inference
----> 2 text = processor.apply_chat_template(
      3     messages, tokenize=False, add_generation_prompt=True
      4 )

File ~/.conda/envs/Qwen2vl/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1845, in PreTrainedTokenizerBase.apply_chat_template(self, conversation, tools, documents, chat_template, add_generation_prompt, tokenize, padding, truncation, max_length, return_tensors, return_dict, return_assistant_tokens_mask, tokenizer_kwargs, **kwargs)
   1843         all_generation_indices.append(generation_indices)
   1844     else:
-> 1845         rendered_chat = compiled_template.render(
   1846             messages=chat,
   1847             tools=tool_schemas,
   1848             documents=documents,
   1849             add_generation_prompt=add_generation_prompt,
   1850             **template_kwargs,
   1851         )
   1852     rendered.append(rendered_chat)
   1854 if not is_batched:

File ~/.conda/envs/Qwen2vl/lib/python3.10/site-packages/jinja2/environment.py:1301, in Template.render(self, *args, **kwargs)
   1299     return self.environment.concat(self.root_render_func(ctx))  # type: ignore
   1300 except Exception:
-> 1301     self.environment.handle_exception()

File ~/.conda/envs/Qwen2vl/lib/python3.10/site-packages/jinja2/environment.py:936, in Environment.handle_exception(self, source)
    931 """Exception handling helper.  This is used internally to either raise
    932 rewritten exceptions or return a rendered traceback for the template.
    933 """
    934 from .debug import rewrite_traceback_stack
--> 936 raise rewrite_traceback_stack(source=source)

File <template>:4, in top-level template code()

TypeError: can only concatenate str (not "list") to str

**Comment by kq-chen** [comment]
try `Qwen/Qwen2-VL-7B-Instruct` not `Qwen/Qwen2-7B-Instruct`

**Comment by Potato-wll** [comment]
问题解决了

**Comment by hello-bluedog** [comment]
请问是怎么解决的

**Comment by bluemoonwencong** [comment]
请问是怎么解决的啊，感谢!   @Potato-wll

**Comment by Potato-wll** [comment]
> 请问是怎么解决的

我模型加载路径错了

**Comment by Potato-wll** [comment]
> 请问是怎么解决的啊，感谢! @Potato-wll

我模型加载的时候选错模型了，选成文本模型了

**Comment by JJ327-1103** [comment]
> 请问是怎么解决的啊，在线的急...

看准你下的模型是VL还是就是文本的（）

**Comment by JJ327-1103** [comment]
> try `Qwen/Qwen2-VL-7B-Instruct` not `Qwen/Qwen2-7B-Instruct`

谢谢！！！！

**Comment by cuiddyy** [comment]
非常感谢！！
