### ISSUE TITLE
精度复现不出来

### ISSUE THREAD

**Issue by luyao-cv** [QwenLM/Qwen2-VL#82]
非常感谢您们的工作，可以麻烦回复下精度对不齐的问题吗？https://github.com/QwenLM/Qwen2-VL/issues/27

**Comment by luyao-cv** [comment]
你好，这边用了新更新的权重，还是没有对齐
是有参数需要修改的吗？

**Comment by logicwong** [comment]
@luyao-cv 在 #27 回复了
