### ISSUE TITLE
Qwen2VL-7B 是否支持温度、topk 等参数

### ISSUE THREAD

**Issue by gudo7208** [QwenLM/Qwen2-VL#91]
Qwen2VL-7B 是否支持温度、topk 等参数
生成时修改温度的参数，生成的内容并没有明显变化，参考 #33 
是不是开源的模型也无法设置温度，只能通过 seed 进行修改？
如果只能通过 seed 进行修改的话，能否提供一个示例代码，感激不尽

**Comment by mokby** [comment]
same issue here

**Comment by gudo7208** [comment]
> same issue here

昨天测试发现，应该是默认贪婪采样的原因，将do_sample = True 以及设置其他 transformers 关于 llm 生成的参数可以出现变化。只是在官方示例代码中没有展示

**Comment by mokby** [comment]
> > same issue here
> 
> 昨天测试发现，应该是默认贪婪采样的原因，将do_sample = True 以及设置其他 transformers 关于 llm 生成的参数可以出现变化。只是在官方示例代码中没有展示

感谢,回头尝试一下
