### ISSUE TITLE
Qwen2-VL-72B权重可以下载么？是否支持VLLM推理

### ISSUE THREAD

**Issue by wuxianyess** [QwenLM/Qwen2-VL#94]
Qwen2-VL-72B可以下载了么，什么时候可以支持下载。此外，能否支持VLLM推理

**Comment by logicwong** [comment]
72b模型的ckpt尚未release

**Comment by thomaszheng** [comment]
借楼提问，72b后续有大致开源的安排的吗？

**Comment by SteveGuo99** [comment]
> @thomaszheng 72B还在迭代中，相关问题可以放到 #75 讨论，欢迎给我们的模型提意见 @wuxianyess 关于VLLM推理请参考 [Deployment](https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#deployment)

大佬，请问vllm是智能用这里贴的vllm分支吗？我用vllm主分支，transformers都升到4.45.0了 依然报错"The checkpoint you are trying to load has model type `qwen2_vl` but Transformers does not recognize this architecture."

**Comment by logicwong** [comment]
@SteveGuo99 先暂时用我们贴的分支吧，给vllm提的pr还没合进去

**Comment by logicwong** [comment]
@SteveGuo99 pr合进主分支了，后续用主分支就行
